PROJECT = softmax

-include ../../scripts/Makefile-syn-catapult.mk

--init:
	touch tb_data/catapult_fpga_rtl_cosim_results.log
	touch tb_data/catapult_asic_rtl_cosim_results.log
	touch tb_data/catapult_fpga_csim_results.log
	touch tb_data/catapult_asic_csim_results.log
.PHONY: --init
