#!/bin/bash

VIVADO_INSTALL_DIR=/opt/Xilinx
VIVADO_VERSION=2017.2

# If running in docker image we would first need to activate the proper conda environment
#. activate hls4ml-py36

# Convert models in keras-models.txt
./convert-keras-models.sh -x -p 3 -f keras-models.txt

# Alternatively, keras-to-hls script can be called, with the model name(s) specified, i.e.:
#./keras-to-hls.sh -p 3 KERAS_1layer KERAS_conv1d_small

# Build the projects generated by keras-to-hls script. Add parameter -s to enable synthesis. -p controls the number of parallel tasks
./build-prj.sh -i ${VIVADO_INSTALL_DIR} -v ${VIVADO_VERSION} -c -s -p 2

# Go through the generated reports and print out basic information
./gather-reports.sh -b

# Clean-up at the end
#./cleanup.sh
