# GENERATED by hls4ml.contrib.runtime_weights -- edit the generator, not this file.
#
# Synthesizes the unmodified @PROJECT_NAME@ HLS IP wrapped with runtime-selected
# weight banks. Contains no board-specific constraints.
#
# The IP is produced by the hls4ml Vitis backend; Vivado is only used to
# implement the packaged result. This is not support for the Vivado HLS backend.
#
# Usage:  vivado -mode batch -source create_runtime_weights.tcl

set project_name  @PROJECT_NAME@
set top_name      @TOP_NAME@
set part          @PART@
set n_banks       @N_BANKS@
set clock_period  @CLOCK_PERIOD@

set here [file normalize [file dirname [info script]]]
set hls_rtl "$here/../${project_name}_prj/solution1/syn/verilog"
set wrap_rtl "$here/rtl"

if {![file isdirectory $hls_rtl]} {
    puts "ERROR: exported HLS RTL not found at $hls_rtl -- run build(synth=True) first"
    exit 1
}
foreach f [list bank_addr_mapper.sv bank_select_latch.sv parameter_bank.sv \
                scalar_bank_mux.sv ${top_name}.sv] {
    if {![file exists "$wrap_rtl/$f"]} {
        puts "ERROR: missing generated source $wrap_rtl/$f"
        exit 1
    }
}

create_project -in_memory -part $part

# unmodified HLS IP
add_files -norecurse [glob "$hls_rtl/*.v"]
# wrapper
add_files -norecurse [glob "$wrap_rtl/*.sv"]
set_property file_type SystemVerilog [get_files "$wrap_rtl/*.sv"]

set_property top $top_name [current_fileset]
update_compile_order -fileset sources_1

# The clock constraint goes in an XDC read before synthesis: the ports do not
# exist until the design is elaborated, so `get_ports` in this script would match
# nothing, and constraining afterwards would leave synthesis unconstrained.
set xdc "$here/${top_name}_clock.xdc"
set fh [open $xdc w]
puts $fh "create_clock -period $clock_period -name ap_clk \[get_ports ap_clk\]"
close $fh
read_xdc $xdc

synth_design -top $top_name -part $part
opt_design

report_utilization -hierarchical -file "$here/utilization.rpt"
report_timing_summary            -file "$here/timing.rpt"
report_drc                       -file "$here/drc.rpt"

puts "runtime-weights wrapper synthesized: top=$top_name banks=$n_banks part=$part"
