# GENERATED by hls4ml.contrib.runtime_weights -- edit the generator, not this file.
#
# Builds a Vivado project containing the unmodified @PROJECT_NAME@ HLS IP wrapped
# with runtime-selected weight banks. Contains no board-specific constraints.
#
# Usage:  vivado -mode batch -source create_runtime_weights.tcl

set project_name  @PROJECT_NAME@
set top_name      @TOP_NAME@
set part          @PART@
set n_banks       @N_BANKS@
set clock_period  @CLOCK_PERIOD@

set here [file normalize [file dirname [info script]]]
set hls_rtl "$here/../${project_name}_prj/solution1/syn/verilog"
set wrap_rtl "$here/rtl"

if {![file isdirectory $hls_rtl]} {
    puts "ERROR: exported HLS RTL not found at $hls_rtl -- run build(synth=True) first"
    exit 1
}
foreach f [list bank_addr_mapper.sv bank_select_latch.sv parameter_bank.sv \
                scalar_bank_mux.sv ${top_name}.sv] {
    if {![file exists "$wrap_rtl/$f"]} {
        puts "ERROR: missing generated source $wrap_rtl/$f"
        exit 1
    }
}

create_project -in_memory -part $part

# unmodified HLS IP
add_files -norecurse [glob "$hls_rtl/*.v"]
# wrapper
add_files -norecurse [glob "$wrap_rtl/*.sv"]
set_property file_type SystemVerilog [get_files "$wrap_rtl/*.sv"]

set_property top $top_name [current_fileset]
update_compile_order -fileset sources_1

create_clock -period $clock_period -name ap_clk [get_ports ap_clk]

synth_design -top $top_name -part $part
opt_design

report_utilization -hierarchical -file "$here/utilization.rpt"
report_timing_summary            -file "$here/timing.rpt"
report_drc                       -file "$here/drc.rpt"

puts "runtime-weights wrapper synthesized: top=$top_name banks=$n_banks part=$part"
