blank_issues_enabled: false
contact_links:
  - name: Question or general problem
    url: https://github.com/fastmachinelearning/hls4ml/discussions/categories/general
    about: Ask on the discussions page. This is the best way to get in touch with us, in particular for a question about hls4ml or a problem that is likely not a bug.
  - name: Propose an idea
    url: https://github.com/fastmachinelearning/hls4ml/discussions/categories/ideas
    about: Float a feature idea with the community before opening a feature request or an RFC.
