// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx690tffg1927-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.330000,HLS_SYN_LAT=17,HLS_SYN_TPT=7,HLS_SYN_MEM=1,HLS_SYN_DSP=48,HLS_SYN_FF=5280,HLS_SYN_LUT=5151}" *)

module myproject (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V,
        data_1_V,
        data_2_V,
        data_3_V,
        data_4_V,
        data_5_V,
        data_6_V,
        data_7_V,
        data_8_V,
        data_9_V,
        res_0_V,
        res_0_V_ap_vld,
        const_size_in,
        const_size_in_ap_vld,
        const_size_out,
        const_size_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 7'b1;
parameter    ap_ST_fsm_pp0_stage1 = 7'b10;
parameter    ap_ST_fsm_pp0_stage2 = 7'b100;
parameter    ap_ST_fsm_pp0_stage3 = 7'b1000;
parameter    ap_ST_fsm_pp0_stage4 = 7'b10000;
parameter    ap_ST_fsm_pp0_stage5 = 7'b100000;
parameter    ap_ST_fsm_pp0_stage6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv16_A = 16'b1010;
parameter    ap_const_lv16_1 = 16'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] data_0_V;
input  [17:0] data_1_V;
input  [17:0] data_2_V;
input  [17:0] data_3_V;
input  [17:0] data_4_V;
input  [17:0] data_5_V;
input  [17:0] data_6_V;
input  [17:0] data_7_V;
input  [17:0] data_8_V;
input  [17:0] data_9_V;
output  [17:0] res_0_V;
output   res_0_V_ap_vld;
output  [15:0] const_size_in;
output   const_size_in_ap_vld;
output  [15:0] const_size_out;
output   const_size_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_0_V_ap_vld;
reg const_size_in_ap_vld;
reg const_size_out_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
wire   [0:0] ap_CS_fsm_pp0_stage6;
reg   [17:0] logits1_0_V_reg_539;
reg   [17:0] logits1_1_V_reg_544;
reg   [17:0] logits1_2_V_reg_549;
reg   [17:0] logits1_3_V_reg_554;
reg   [17:0] logits1_4_V_reg_559;
reg   [17:0] logits1_5_V_reg_564;
reg   [17:0] logits1_6_V_reg_569;
reg   [17:0] logits1_7_V_reg_574;
reg   [17:0] logits1_8_V_reg_579;
reg   [17:0] logits1_9_V_reg_584;
reg   [17:0] logits1_10_V_reg_589;
reg   [17:0] logits1_11_V_reg_594;
reg   [17:0] logits1_12_V_reg_599;
reg   [17:0] logits1_13_V_reg_604;
reg   [17:0] logits1_14_V_reg_609;
reg   [17:0] logits1_15_V_reg_614;
reg   [17:0] logits1_16_V_reg_619;
reg   [17:0] logits1_17_V_reg_624;
reg   [17:0] logits1_18_V_reg_629;
reg   [17:0] logits1_19_V_reg_634;
reg   [17:0] logits1_20_V_reg_639;
reg   [17:0] logits1_21_V_reg_644;
reg   [17:0] logits1_22_V_reg_649;
reg   [17:0] logits1_23_V_reg_654;
reg   [17:0] logits1_24_V_reg_659;
reg   [17:0] logits1_25_V_reg_664;
reg   [17:0] logits1_26_V_reg_669;
reg   [17:0] logits1_27_V_reg_674;
reg   [17:0] logits1_28_V_reg_679;
reg   [17:0] logits1_29_V_reg_684;
reg   [17:0] logits1_30_V_reg_689;
reg   [17:0] logits1_31_V_reg_694;
reg   [17:0] layer1_out_0_V_reg_699;
reg   [17:0] layer1_out_1_V_reg_704;
reg   [17:0] layer1_out_2_V_reg_709;
reg   [17:0] layer1_out_3_V_reg_714;
reg   [17:0] layer1_out_4_V_reg_719;
reg   [17:0] layer1_out_5_V_reg_724;
reg   [17:0] layer1_out_6_V_reg_729;
reg   [17:0] layer1_out_7_V_reg_734;
reg   [17:0] layer1_out_8_V_reg_739;
reg   [17:0] layer1_out_9_V_reg_744;
reg   [17:0] layer1_out_10_V_reg_749;
reg   [17:0] layer1_out_11_V_reg_754;
reg   [17:0] layer1_out_12_V_reg_759;
reg   [17:0] layer1_out_13_V_reg_764;
reg   [17:0] layer1_out_14_V_reg_769;
reg   [17:0] layer1_out_15_V_reg_774;
reg   [17:0] layer1_out_16_V_reg_779;
reg   [17:0] layer1_out_17_V_reg_784;
reg   [17:0] layer1_out_18_V_reg_789;
reg   [17:0] layer1_out_19_V_reg_794;
reg   [17:0] layer1_out_20_V_reg_799;
reg   [17:0] layer1_out_21_V_reg_804;
reg   [17:0] layer1_out_22_V_reg_809;
reg   [17:0] layer1_out_23_V_reg_814;
reg   [17:0] layer1_out_24_V_reg_819;
reg   [17:0] layer1_out_25_V_reg_824;
reg   [17:0] layer1_out_26_V_reg_829;
reg   [17:0] layer1_out_27_V_reg_834;
reg   [17:0] layer1_out_28_V_reg_839;
reg   [17:0] layer1_out_29_V_reg_844;
reg   [17:0] layer1_out_30_V_reg_849;
reg   [17:0] layer1_out_31_V_reg_854;
wire   [17:0] grp_compute_layer_0_0_0_1_fu_169_ap_return;
reg   [17:0] logits2_0_V_reg_859;
reg    ap_enable_reg_pp0_iter0_preg;
wire   [0:0] ap_CS_fsm_pp0_stage3;
reg    grp_compute_layer_0_0_0_s_fu_145_ap_start;
wire    grp_compute_layer_0_0_0_s_fu_145_ap_done;
wire    grp_compute_layer_0_0_0_s_fu_145_ap_idle;
wire    grp_compute_layer_0_0_0_s_fu_145_ap_ready;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_0;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_1;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_2;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_3;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_4;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_5;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_6;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_7;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_8;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_9;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_10;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_11;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_12;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_13;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_14;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_15;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_16;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_17;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_18;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_19;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_20;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_21;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_22;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_23;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_24;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_25;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_26;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_27;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_28;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_29;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_30;
wire   [17:0] grp_compute_layer_0_0_0_s_fu_145_ap_return_31;
wire    grp_compute_layer_0_0_0_1_fu_169_ap_start;
wire    grp_compute_layer_0_0_0_1_fu_169_ap_done;
wire    grp_compute_layer_0_0_0_1_fu_169_ap_idle;
wire    grp_compute_layer_0_0_0_1_fu_169_ap_ready;
wire   [17:0] call_ret2_relu_fu_205_ap_return_0;
wire   [17:0] call_ret2_relu_fu_205_ap_return_1;
wire   [17:0] call_ret2_relu_fu_205_ap_return_2;
wire   [17:0] call_ret2_relu_fu_205_ap_return_3;
wire   [17:0] call_ret2_relu_fu_205_ap_return_4;
wire   [17:0] call_ret2_relu_fu_205_ap_return_5;
wire   [17:0] call_ret2_relu_fu_205_ap_return_6;
wire   [17:0] call_ret2_relu_fu_205_ap_return_7;
wire   [17:0] call_ret2_relu_fu_205_ap_return_8;
wire   [17:0] call_ret2_relu_fu_205_ap_return_9;
wire   [17:0] call_ret2_relu_fu_205_ap_return_10;
wire   [17:0] call_ret2_relu_fu_205_ap_return_11;
wire   [17:0] call_ret2_relu_fu_205_ap_return_12;
wire   [17:0] call_ret2_relu_fu_205_ap_return_13;
wire   [17:0] call_ret2_relu_fu_205_ap_return_14;
wire   [17:0] call_ret2_relu_fu_205_ap_return_15;
wire   [17:0] call_ret2_relu_fu_205_ap_return_16;
wire   [17:0] call_ret2_relu_fu_205_ap_return_17;
wire   [17:0] call_ret2_relu_fu_205_ap_return_18;
wire   [17:0] call_ret2_relu_fu_205_ap_return_19;
wire   [17:0] call_ret2_relu_fu_205_ap_return_20;
wire   [17:0] call_ret2_relu_fu_205_ap_return_21;
wire   [17:0] call_ret2_relu_fu_205_ap_return_22;
wire   [17:0] call_ret2_relu_fu_205_ap_return_23;
wire   [17:0] call_ret2_relu_fu_205_ap_return_24;
wire   [17:0] call_ret2_relu_fu_205_ap_return_25;
wire   [17:0] call_ret2_relu_fu_205_ap_return_26;
wire   [17:0] call_ret2_relu_fu_205_ap_return_27;
wire   [17:0] call_ret2_relu_fu_205_ap_return_28;
wire   [17:0] call_ret2_relu_fu_205_ap_return_29;
wire   [17:0] call_ret2_relu_fu_205_ap_return_30;
wire   [17:0] call_ret2_relu_fu_205_ap_return_31;
wire    grp_sigmoid_fu_241_ap_start;
wire    grp_sigmoid_fu_241_ap_done;
wire    grp_sigmoid_fu_241_ap_idle;
wire    grp_sigmoid_fu_241_ap_ready;
wire   [9:0] grp_sigmoid_fu_241_ap_return;
reg   [6:0] ap_NS_fsm;
reg    ap_grp_compute_layer_0_0_0_s_fu_145_ap_start;
reg    ap_reg_grp_compute_layer_0_0_0_1_fu_169_ap_start;
wire   [0:0] ap_CS_fsm_pp0_stage1;
reg    ap_reg_grp_sigmoid_fu_241_ap_start;
reg    ap_pipeline_idle_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'b1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_preg = 1'b0;
#0 ap_reg_grp_compute_layer_0_0_0_1_fu_169_ap_start = 1'b0;
#0 ap_reg_grp_sigmoid_fu_241_ap_start = 1'b0;
end

compute_layer_0_0_0_s grp_compute_layer_0_0_0_s_fu_145(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_layer_0_0_0_s_fu_145_ap_start),
    .ap_done(grp_compute_layer_0_0_0_s_fu_145_ap_done),
    .ap_idle(grp_compute_layer_0_0_0_s_fu_145_ap_idle),
    .ap_ready(grp_compute_layer_0_0_0_s_fu_145_ap_ready),
    .data_0_V_read(data_0_V),
    .data_1_V_read(data_1_V),
    .data_2_V_read(data_2_V),
    .data_3_V_read(data_3_V),
    .data_4_V_read(data_4_V),
    .data_5_V_read(data_5_V),
    .data_6_V_read(data_6_V),
    .data_7_V_read(data_7_V),
    .data_8_V_read(data_8_V),
    .data_9_V_read(data_9_V),
    .ap_return_0(grp_compute_layer_0_0_0_s_fu_145_ap_return_0),
    .ap_return_1(grp_compute_layer_0_0_0_s_fu_145_ap_return_1),
    .ap_return_2(grp_compute_layer_0_0_0_s_fu_145_ap_return_2),
    .ap_return_3(grp_compute_layer_0_0_0_s_fu_145_ap_return_3),
    .ap_return_4(grp_compute_layer_0_0_0_s_fu_145_ap_return_4),
    .ap_return_5(grp_compute_layer_0_0_0_s_fu_145_ap_return_5),
    .ap_return_6(grp_compute_layer_0_0_0_s_fu_145_ap_return_6),
    .ap_return_7(grp_compute_layer_0_0_0_s_fu_145_ap_return_7),
    .ap_return_8(grp_compute_layer_0_0_0_s_fu_145_ap_return_8),
    .ap_return_9(grp_compute_layer_0_0_0_s_fu_145_ap_return_9),
    .ap_return_10(grp_compute_layer_0_0_0_s_fu_145_ap_return_10),
    .ap_return_11(grp_compute_layer_0_0_0_s_fu_145_ap_return_11),
    .ap_return_12(grp_compute_layer_0_0_0_s_fu_145_ap_return_12),
    .ap_return_13(grp_compute_layer_0_0_0_s_fu_145_ap_return_13),
    .ap_return_14(grp_compute_layer_0_0_0_s_fu_145_ap_return_14),
    .ap_return_15(grp_compute_layer_0_0_0_s_fu_145_ap_return_15),
    .ap_return_16(grp_compute_layer_0_0_0_s_fu_145_ap_return_16),
    .ap_return_17(grp_compute_layer_0_0_0_s_fu_145_ap_return_17),
    .ap_return_18(grp_compute_layer_0_0_0_s_fu_145_ap_return_18),
    .ap_return_19(grp_compute_layer_0_0_0_s_fu_145_ap_return_19),
    .ap_return_20(grp_compute_layer_0_0_0_s_fu_145_ap_return_20),
    .ap_return_21(grp_compute_layer_0_0_0_s_fu_145_ap_return_21),
    .ap_return_22(grp_compute_layer_0_0_0_s_fu_145_ap_return_22),
    .ap_return_23(grp_compute_layer_0_0_0_s_fu_145_ap_return_23),
    .ap_return_24(grp_compute_layer_0_0_0_s_fu_145_ap_return_24),
    .ap_return_25(grp_compute_layer_0_0_0_s_fu_145_ap_return_25),
    .ap_return_26(grp_compute_layer_0_0_0_s_fu_145_ap_return_26),
    .ap_return_27(grp_compute_layer_0_0_0_s_fu_145_ap_return_27),
    .ap_return_28(grp_compute_layer_0_0_0_s_fu_145_ap_return_28),
    .ap_return_29(grp_compute_layer_0_0_0_s_fu_145_ap_return_29),
    .ap_return_30(grp_compute_layer_0_0_0_s_fu_145_ap_return_30),
    .ap_return_31(grp_compute_layer_0_0_0_s_fu_145_ap_return_31)
);

compute_layer_0_0_0_1 grp_compute_layer_0_0_0_1_fu_169(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_layer_0_0_0_1_fu_169_ap_start),
    .ap_done(grp_compute_layer_0_0_0_1_fu_169_ap_done),
    .ap_idle(grp_compute_layer_0_0_0_1_fu_169_ap_idle),
    .ap_ready(grp_compute_layer_0_0_0_1_fu_169_ap_ready),
    .data_0_V_read(layer1_out_0_V_reg_699),
    .data_1_V_read(layer1_out_1_V_reg_704),
    .data_2_V_read(layer1_out_2_V_reg_709),
    .data_3_V_read(layer1_out_3_V_reg_714),
    .data_4_V_read(layer1_out_4_V_reg_719),
    .data_5_V_read(layer1_out_5_V_reg_724),
    .data_6_V_read(layer1_out_6_V_reg_729),
    .data_7_V_read(layer1_out_7_V_reg_734),
    .data_8_V_read(layer1_out_8_V_reg_739),
    .data_9_V_read(layer1_out_9_V_reg_744),
    .data_10_V_read(layer1_out_10_V_reg_749),
    .data_11_V_read(layer1_out_11_V_reg_754),
    .data_12_V_read(layer1_out_12_V_reg_759),
    .data_13_V_read(layer1_out_13_V_reg_764),
    .data_14_V_read(layer1_out_14_V_reg_769),
    .data_15_V_read(layer1_out_15_V_reg_774),
    .data_16_V_read(layer1_out_16_V_reg_779),
    .data_17_V_read(layer1_out_17_V_reg_784),
    .data_18_V_read(layer1_out_18_V_reg_789),
    .data_19_V_read(layer1_out_19_V_reg_794),
    .data_20_V_read(layer1_out_20_V_reg_799),
    .data_21_V_read(layer1_out_21_V_reg_804),
    .data_22_V_read(layer1_out_22_V_reg_809),
    .data_23_V_read(layer1_out_23_V_reg_814),
    .data_24_V_read(layer1_out_24_V_reg_819),
    .data_25_V_read(layer1_out_25_V_reg_824),
    .data_26_V_read(layer1_out_26_V_reg_829),
    .data_27_V_read(layer1_out_27_V_reg_834),
    .data_28_V_read(layer1_out_28_V_reg_839),
    .data_29_V_read(layer1_out_29_V_reg_844),
    .data_30_V_read(layer1_out_30_V_reg_849),
    .data_31_V_read(layer1_out_31_V_reg_854),
    .ap_return(grp_compute_layer_0_0_0_1_fu_169_ap_return)
);

relu call_ret2_relu_fu_205(
    .data_0_V_read(logits1_0_V_reg_539),
    .data_1_V_read(logits1_1_V_reg_544),
    .data_2_V_read(logits1_2_V_reg_549),
    .data_3_V_read(logits1_3_V_reg_554),
    .data_4_V_read(logits1_4_V_reg_559),
    .data_5_V_read(logits1_5_V_reg_564),
    .data_6_V_read(logits1_6_V_reg_569),
    .data_7_V_read(logits1_7_V_reg_574),
    .data_8_V_read(logits1_8_V_reg_579),
    .data_9_V_read(logits1_9_V_reg_584),
    .data_10_V_read(logits1_10_V_reg_589),
    .data_11_V_read(logits1_11_V_reg_594),
    .data_12_V_read(logits1_12_V_reg_599),
    .data_13_V_read(logits1_13_V_reg_604),
    .data_14_V_read(logits1_14_V_reg_609),
    .data_15_V_read(logits1_15_V_reg_614),
    .data_16_V_read(logits1_16_V_reg_619),
    .data_17_V_read(logits1_17_V_reg_624),
    .data_18_V_read(logits1_18_V_reg_629),
    .data_19_V_read(logits1_19_V_reg_634),
    .data_20_V_read(logits1_20_V_reg_639),
    .data_21_V_read(logits1_21_V_reg_644),
    .data_22_V_read(logits1_22_V_reg_649),
    .data_23_V_read(logits1_23_V_reg_654),
    .data_24_V_read(logits1_24_V_reg_659),
    .data_25_V_read(logits1_25_V_reg_664),
    .data_26_V_read(logits1_26_V_reg_669),
    .data_27_V_read(logits1_27_V_reg_674),
    .data_28_V_read(logits1_28_V_reg_679),
    .data_29_V_read(logits1_29_V_reg_684),
    .data_30_V_read(logits1_30_V_reg_689),
    .data_31_V_read(logits1_31_V_reg_694),
    .ap_return_0(call_ret2_relu_fu_205_ap_return_0),
    .ap_return_1(call_ret2_relu_fu_205_ap_return_1),
    .ap_return_2(call_ret2_relu_fu_205_ap_return_2),
    .ap_return_3(call_ret2_relu_fu_205_ap_return_3),
    .ap_return_4(call_ret2_relu_fu_205_ap_return_4),
    .ap_return_5(call_ret2_relu_fu_205_ap_return_5),
    .ap_return_6(call_ret2_relu_fu_205_ap_return_6),
    .ap_return_7(call_ret2_relu_fu_205_ap_return_7),
    .ap_return_8(call_ret2_relu_fu_205_ap_return_8),
    .ap_return_9(call_ret2_relu_fu_205_ap_return_9),
    .ap_return_10(call_ret2_relu_fu_205_ap_return_10),
    .ap_return_11(call_ret2_relu_fu_205_ap_return_11),
    .ap_return_12(call_ret2_relu_fu_205_ap_return_12),
    .ap_return_13(call_ret2_relu_fu_205_ap_return_13),
    .ap_return_14(call_ret2_relu_fu_205_ap_return_14),
    .ap_return_15(call_ret2_relu_fu_205_ap_return_15),
    .ap_return_16(call_ret2_relu_fu_205_ap_return_16),
    .ap_return_17(call_ret2_relu_fu_205_ap_return_17),
    .ap_return_18(call_ret2_relu_fu_205_ap_return_18),
    .ap_return_19(call_ret2_relu_fu_205_ap_return_19),
    .ap_return_20(call_ret2_relu_fu_205_ap_return_20),
    .ap_return_21(call_ret2_relu_fu_205_ap_return_21),
    .ap_return_22(call_ret2_relu_fu_205_ap_return_22),
    .ap_return_23(call_ret2_relu_fu_205_ap_return_23),
    .ap_return_24(call_ret2_relu_fu_205_ap_return_24),
    .ap_return_25(call_ret2_relu_fu_205_ap_return_25),
    .ap_return_26(call_ret2_relu_fu_205_ap_return_26),
    .ap_return_27(call_ret2_relu_fu_205_ap_return_27),
    .ap_return_28(call_ret2_relu_fu_205_ap_return_28),
    .ap_return_29(call_ret2_relu_fu_205_ap_return_29),
    .ap_return_30(call_ret2_relu_fu_205_ap_return_30),
    .ap_return_31(call_ret2_relu_fu_205_ap_return_31)
);

sigmoid grp_sigmoid_fu_241(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sigmoid_fu_241_ap_start),
    .ap_done(grp_sigmoid_fu_241_ap_done),
    .ap_idle(grp_sigmoid_fu_241_ap_idle),
    .ap_ready(grp_sigmoid_fu_241_ap_ready),
    .data_V_read(logits2_0_V_reg_859),
    .ap_return(grp_sigmoid_fu_241_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_preg <= 1'b0;
    end else begin
        if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
            ap_enable_reg_pp0_iter0_preg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & ~(1'b1 == ap_enable_reg_pp0_iter1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_compute_layer_0_0_0_1_fu_169_ap_start <= 1'b0;
    end else begin
        if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
            ap_reg_grp_compute_layer_0_0_0_1_fu_169_ap_start <= 1'b1;
        end else if ((1'b1 == grp_compute_layer_0_0_0_1_fu_169_ap_ready)) begin
            ap_reg_grp_compute_layer_0_0_0_1_fu_169_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_sigmoid_fu_241_ap_start <= 1'b0;
    end else begin
        if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
            ap_reg_grp_sigmoid_fu_241_ap_start <= 1'b1;
        end else if ((1'b1 == grp_sigmoid_fu_241_ap_ready)) begin
            ap_reg_grp_sigmoid_fu_241_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        layer1_out_0_V_reg_699 <= call_ret2_relu_fu_205_ap_return_0;
        layer1_out_10_V_reg_749 <= call_ret2_relu_fu_205_ap_return_10;
        layer1_out_11_V_reg_754 <= call_ret2_relu_fu_205_ap_return_11;
        layer1_out_12_V_reg_759 <= call_ret2_relu_fu_205_ap_return_12;
        layer1_out_13_V_reg_764 <= call_ret2_relu_fu_205_ap_return_13;
        layer1_out_14_V_reg_769 <= call_ret2_relu_fu_205_ap_return_14;
        layer1_out_15_V_reg_774 <= call_ret2_relu_fu_205_ap_return_15;
        layer1_out_16_V_reg_779 <= call_ret2_relu_fu_205_ap_return_16;
        layer1_out_17_V_reg_784 <= call_ret2_relu_fu_205_ap_return_17;
        layer1_out_18_V_reg_789 <= call_ret2_relu_fu_205_ap_return_18;
        layer1_out_19_V_reg_794 <= call_ret2_relu_fu_205_ap_return_19;
        layer1_out_1_V_reg_704 <= call_ret2_relu_fu_205_ap_return_1;
        layer1_out_20_V_reg_799 <= call_ret2_relu_fu_205_ap_return_20;
        layer1_out_21_V_reg_804 <= call_ret2_relu_fu_205_ap_return_21;
        layer1_out_22_V_reg_809 <= call_ret2_relu_fu_205_ap_return_22;
        layer1_out_23_V_reg_814 <= call_ret2_relu_fu_205_ap_return_23;
        layer1_out_24_V_reg_819 <= call_ret2_relu_fu_205_ap_return_24;
        layer1_out_25_V_reg_824 <= call_ret2_relu_fu_205_ap_return_25;
        layer1_out_26_V_reg_829 <= call_ret2_relu_fu_205_ap_return_26;
        layer1_out_27_V_reg_834 <= call_ret2_relu_fu_205_ap_return_27;
        layer1_out_28_V_reg_839 <= call_ret2_relu_fu_205_ap_return_28;
        layer1_out_29_V_reg_844 <= call_ret2_relu_fu_205_ap_return_29;
        layer1_out_2_V_reg_709 <= call_ret2_relu_fu_205_ap_return_2;
        layer1_out_30_V_reg_849 <= call_ret2_relu_fu_205_ap_return_30;
        layer1_out_31_V_reg_854 <= call_ret2_relu_fu_205_ap_return_31;
        layer1_out_3_V_reg_714 <= call_ret2_relu_fu_205_ap_return_3;
        layer1_out_4_V_reg_719 <= call_ret2_relu_fu_205_ap_return_4;
        layer1_out_5_V_reg_724 <= call_ret2_relu_fu_205_ap_return_5;
        layer1_out_6_V_reg_729 <= call_ret2_relu_fu_205_ap_return_6;
        layer1_out_7_V_reg_734 <= call_ret2_relu_fu_205_ap_return_7;
        layer1_out_8_V_reg_739 <= call_ret2_relu_fu_205_ap_return_8;
        layer1_out_9_V_reg_744 <= call_ret2_relu_fu_205_ap_return_9;
        logits2_0_V_reg_859 <= grp_compute_layer_0_0_0_1_fu_169_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
        logits1_0_V_reg_539 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_0;
        logits1_10_V_reg_589 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_10;
        logits1_11_V_reg_594 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_11;
        logits1_12_V_reg_599 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_12;
        logits1_13_V_reg_604 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_13;
        logits1_14_V_reg_609 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_14;
        logits1_15_V_reg_614 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_15;
        logits1_16_V_reg_619 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_16;
        logits1_17_V_reg_624 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_17;
        logits1_18_V_reg_629 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_18;
        logits1_19_V_reg_634 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_19;
        logits1_1_V_reg_544 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_1;
        logits1_20_V_reg_639 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_20;
        logits1_21_V_reg_644 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_21;
        logits1_22_V_reg_649 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_22;
        logits1_23_V_reg_654 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_23;
        logits1_24_V_reg_659 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_24;
        logits1_25_V_reg_664 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_25;
        logits1_26_V_reg_669 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_26;
        logits1_27_V_reg_674 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_27;
        logits1_28_V_reg_679 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_28;
        logits1_29_V_reg_684 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_29;
        logits1_2_V_reg_549 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_2;
        logits1_30_V_reg_689 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_30;
        logits1_31_V_reg_694 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_31;
        logits1_3_V_reg_554 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_3;
        logits1_4_V_reg_559 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_4;
        logits1_5_V_reg_564 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_5;
        logits1_6_V_reg_569 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_6;
        logits1_7_V_reg_574 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_7;
        logits1_8_V_reg_579 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_8;
        logits1_9_V_reg_584 <= grp_compute_layer_0_0_0_s_fu_145_ap_return_9;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_preg;
    end
end

always @ (*) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(ap_start == 1'b0))) begin
        ap_grp_compute_layer_0_0_0_s_fu_145_ap_start = 1'b1;
    end else begin
        ap_grp_compute_layer_0_0_0_s_fu_145_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_pipeline_idle_pp0 = 1'b1;
    end else begin
        ap_pipeline_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        const_size_in_ap_vld = 1'b1;
    end else begin
        const_size_in_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        const_size_out_ap_vld = 1'b1;
    end else begin
        const_size_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_grp_compute_layer_0_0_0_s_fu_145_ap_start)) begin
        grp_compute_layer_0_0_0_s_fu_145_ap_start = ap_grp_compute_layer_0_0_0_s_fu_145_ap_start;
    end else begin
        grp_compute_layer_0_0_0_s_fu_145_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        res_0_V_ap_vld = 1'b1;
    end else begin
        res_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & ~((1'b0 == ap_start) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage2;
        end
        ap_ST_fsm_pp0_stage2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage3;
        end
        ap_ST_fsm_pp0_stage3 : begin
            if (~(1'b1 == ap_pipeline_idle_pp0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage5;
        end
        ap_ST_fsm_pp0_stage5 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage6;
        end
        ap_ST_fsm_pp0_stage6 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[ap_const_lv32_6];

assign const_size_in = ap_const_lv16_A;

assign const_size_out = ap_const_lv16_1;

assign grp_compute_layer_0_0_0_1_fu_169_ap_start = ap_reg_grp_compute_layer_0_0_0_1_fu_169_ap_start;

assign grp_sigmoid_fu_241_ap_start = ap_reg_grp_sigmoid_fu_241_ap_start;

assign res_0_V = grp_sigmoid_fu_241_ap_return;

endmodule //myproject
