#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("data_0_V", 18, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("data_1_V", 18, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("data_2_V", 18, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("data_3_V", 18, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("data_4_V", 18, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("data_5_V", 18, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("data_6_V", 18, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("data_7_V", 18, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("data_8_V", 18, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("data_9_V", 18, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("res_0_V", 18, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("res_0_V_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("const_size_in", 16, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("const_size_in_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
	Port_Property("const_size_out", 16, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("const_size_out_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "myproject";
