"""Post-export packaging: wrap an already-synthesized hls4ml IP with banked
parameter memories.

This runs AFTER ``build(synth=True)``. It only reads the generated project -- the
HLS compute IP is never modified, and its RTL stays byte-identical.

Not provided, by design: AXI or board support, any driver, a C++ wrapper, any
automatic change to ``BramFactor``, and any support for overlapping transactions.
Bank selection is idle-time only.
"""

import hashlib
import json
import os
import shutil

from hls4ml.contrib.runtime_weights import interface
from hls4ml.writer.external_parameters import MANIFEST_FILENAME

# Verified independently of the writer: if hls4ml starts emitting a different
# schema, packaging must fail loudly rather than misread the new semantics.
EXPECTED_SCHEMA = 'hls4ml.external_parameter_manifest/v1'
SUPPORTED_SCHEMA_VERSIONS = frozenset({1})

# Only the Vitis flow has been verified end to end. Note this is about which
# hls4ml backend produced the IP; Vivado is still used to implement the result.
SUPPORTED_BACKENDS = frozenset({'Vitis'})


class InterfaceUnsupported(Exception):
    """The model has an external parameter this version cannot bank."""


# The ownership latch drives ap_start/ap_ready directly, so anything else
# (ap_ctrl_chain, ap_ctrl_none) would be mis-driven rather than merely unsupported.
REQUIRED_CONTROL_PROTOCOL = 'ap_ctrl_hs'

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'templates')
STATIC_MODULES = ['bank_addr_mapper.sv', 'bank_select_latch.sv', 'parameter_bank.sv', 'scalar_bank_mux.sv']


def _next_pow2(n):
    return 1 << (n - 1).bit_length() if n > 1 else 1


def fingerprint_ip(project_dir, project_name):
    """SHA-256 over the exported compute artifacts: the RTL and the data files that
    initialize its generated ROMs.

    This records the state of the IP; on its own it proves nothing about what the
    IP looked like earlier. Comparing a fingerprint taken before packaging with
    one taken after is what shows the IP was left alone.
    """
    verilog = interface.solution_verilog_dir(project_dir, project_name)
    entries = []
    for name in sorted(os.listdir(verilog)):
        # A .dat is part of the compute artifact: $readmemh loads it into a
        # generated ROM at elaboration, so it changes what the IP computes.
        if name.endswith(('.v', '.dat')):
            digest = hashlib.sha256(open(os.path.join(verilog, name), 'rb').read()).hexdigest()
            entries.append(f'{digest}  {name}')
    combined = hashlib.sha256('\n'.join(entries).encode()).hexdigest()
    return {'combined': combined, 'files': entries}


# The bank count is fixed when the wrapper is generated: the packed memory image,
# runtime_weights.json and the bank stride all encode it, so an elaboration-time
# override would produce a design inconsistent with its own artifacts. Re-banking
# costs a packager run, not an HLS run. Both constants are emitted as localparams
# ahead of the port list so the ports can reference them.
CONTROL_PORTS = {'ap_clk', 'ap_rst', 'ap_start', 'ap_done', 'ap_ready', 'ap_idle'}


def _classify_ports(rtl_ports, banked):
    """Split the IP's real port list into control / banked / pass-through.

    The banked names come from interface.verify(), which resolved them against the
    generated RTL; nothing here reconstructs a Vitis signal name.
    """
    owned = set(CONTROL_PORTS)
    for p in banked:
        if p['expected_interface_kind'] == 'bram':
            owned.update(p['actual_signals'].values())
        elif p['expected_interface_kind'] == 'scalar_bundle':
            owned.update(p['actual_ports'])

    return [p for p in rtl_ports if p['name'] not in owned]


def _decl(port, prefix=''):
    direction = 'input  wire' if port['dir'] == 'input' else 'output wire'
    width = '' if port['width'] == 1 else f'[{port["width"] - 1}:0] '
    return f'    {direction} {width}{prefix}{port["name"]}'


def _emit_top(f, project_name, banked, rtl_ports, n_banks, bank_id_width, control):
    """Generate the integration top.

    Every port of the wrapped IP is declared and connected explicitly: control to
    the ownership latch, banked parameters to their memories, and everything else
    (the network inputs and outputs) passed through to this module's own ports.
    No implicit .* connection is used -- it cannot resolve here, because the IP's
    data ports are not nets in this scope.
    """
    bram = [p for p in banked if p['expected_interface_kind'] == 'bram']
    scalar = [p for p in banked if p['expected_interface_kind'] == 'scalar_bundle']
    passthrough = _classify_ports(rtl_ports, banked)

    f.write('// GENERATED by hls4ml.contrib.runtime_weights -- do not edit.\n')
    f.write(f'// Wraps the unmodified {project_name} IP with runtime-selected weight banks.\n')
    f.write(f'// Control protocol: {control}. Bank selection is idle-time only.\n\n')
    f.write('`timescale 1 ns / 1 ps\n')
    f.write('`default_nettype none\n\n')
    f.write(f'module {project_name}_runtime_weights #(\n')
    init_params = [f'    parameter {p["name"].upper()}_INIT_HEX = ""' for p in bram]
    f.write(',\n'.join(init_params) if init_params else '    parameter UNUSED = 0')
    f.write('\n) (\n')

    lines = [
        '    input  wire ap_clk',
        '    input  wire ap_rst',
        '',
        '    // transaction boundary',
        '    input  wire ext_ap_start',
        f'    input  wire [{bank_id_width - 1}:0] ext_bank_id',
        '    output wire ext_ap_ready',
        '    output wire ext_ap_done',
        '    output wire ext_bank_id_bad',
        '',
    ]
    if passthrough:
        lines.append('    // network data ports, passed through to the IP')
        lines.extend(_decl(p) for p in passthrough)
        lines.append('')
    lines.append('    // loader (accepted only while idle)')
    for p in bram:
        n = p['name']
        word_bits = max((p['expected_depth'] - 1).bit_length(), 1)
        lines += [
            f'    input  wire ld_{n}_req',
            f'    input  wire [{bank_id_width - 1}:0] ld_{n}_bank',
            f'    input  wire [{word_bits - 1}:0] ld_{n}_word',
            f'    input  wire [{p["actual_data_width"] - 1}:0] ld_{n}_wdata',
            f'    output wire ld_{n}_accept',
            f'    output wire ld_{n}_reject',
        ]
    for p in scalar:
        n = p['name']
        idx_bits = max((p['n_scalars'] - 1).bit_length(), 1)
        lines += [
            f'    input  wire ld_{n}_we',
            f'    input  wire [{bank_id_width - 1}:0] ld_{n}_bank',
            f'    input  wire [{idx_bits - 1}:0] ld_{n}_idx',
            f'    input  wire [{p["actual_width"] - 1}:0] ld_{n}_data',
            f'    output wire ld_{n}_accept',
            f'    output wire ld_{n}_reject',
        ]
    lines += [
        '',
        '    // observability',
        f'    output wire [{bank_id_width - 1}:0] cur_bank_id',
        '    output wire busy',
        '    output wire quiescent',
    ]

    body = [ln for ln in lines if ln.strip()]
    for ln in lines:
        if not ln.strip():
            f.write('\n')
        else:
            last = ln is body[-1]
            f.write(ln + ('\n' if last else ',\n'))
    f.write(');\n\n')

    f.write(f'  localparam int N_BANKS       = {n_banks};\n')
    f.write(f'  localparam int BANK_ID_WIDTH = {bank_id_width};\n\n')
    f.write('  wire hls_ap_start, hls_ap_done, hls_ap_idle, hls_ap_ready;\n\n')
    f.write('  bank_select_latch #(.BANK_ID_WIDTH(BANK_ID_WIDTH), .N_BANKS(N_BANKS)) u_latch (\n')
    f.write('      .ap_clk(ap_clk), .ap_rst(ap_rst),\n')
    f.write('      .ext_ap_start(ext_ap_start), .ext_bank_id(ext_bank_id),\n')
    f.write('      .ext_ap_ready(ext_ap_ready), .ext_bank_id_bad(ext_bank_id_bad),\n')
    f.write('      .hls_ap_start(hls_ap_start), .hls_ap_ready(hls_ap_ready),\n')
    f.write('      .hls_ap_idle(hls_ap_idle), .hls_ap_done(hls_ap_done),\n')
    f.write('      .cur_bank_id(cur_bank_id), .busy(busy), .quiescent(quiescent));\n\n')
    f.write('  assign ext_ap_done = hls_ap_done;\n\n')

    for p in bram:
        n, dw = p['name'], p['actual_data_width']
        pw = p['actual_port_width']
        sig = p['actual_signals']
        stride = _next_pow2(p['expected_depth'])
        # declared at the PHYSICAL width the IP drives, not the logical word width:
        # parameter_bank pads between the two explicitly
        f.write(f'  wire [{p["actual_addr_width"] - 1}:0] {sig["addr_a"]}, {sig["addr_b"]};\n')
        f.write(f'  wire {sig["en_a"]}, {sig["en_b"]}, {sig["clk_a"]}, {sig["rst_a"]};\n')
        f.write(f'  wire [{pw - 1}:0] {sig["din_a"]}, {sig["dout_a"]}, {sig["dout_b"]};\n')
        f.write(f'  wire [{pw // 8 - 1}:0] {sig["wen_a"]};\n')
        f.write(f'  parameter_bank #(.DATA_WIDTH({dw}), .PORT_WIDTH({pw}),\n')
        f.write(f'      .HLS_ADDR_WIDTH({p["actual_addr_width"]}),\n')
        f.write(f'      .WORD_BYTES({p["actual_addr_stride"]}), .LOCAL_WORDS({p["expected_depth"]}),\n')
        f.write('      .N_BANKS(N_BANKS), .BANK_ID_WIDTH(BANK_ID_WIDTH),\n')
        f.write(f'      .BANK_STRIDE_WORDS({stride}), .INIT_HEX({n.upper()}_INIT_HEX)) u_{n} (\n')
        f.write('      .ap_clk(ap_clk), .ap_rst(ap_rst), .cur_bank_id(cur_bank_id), .quiescent(quiescent),\n')
        f.write(f'      .hls_Addr_A({sig["addr_a"]}), .hls_EN_A({sig["en_a"]}), .hls_WEN_A({sig["wen_a"]}),\n')
        f.write(f'      .hls_Din_A({sig["din_a"]}), .hls_Dout_A({sig["dout_a"]}), .hls_Rst_A({sig["rst_a"]}),\n')
        f.write(f'      .hls_Addr_B({sig["addr_b"]}), .hls_EN_B({sig["en_b"]}), .hls_Dout_B({sig["dout_b"]}),\n')
        f.write(f'      .ld_req(ld_{n}_req), .ld_bank(ld_{n}_bank), .ld_word(ld_{n}_word),\n')
        f.write(f'      .ld_wdata(ld_{n}_wdata),\n')
        f.write(f'      .ld_accept(ld_{n}_accept), .ld_reject(ld_{n}_reject),\n')
        f.write('      .addr_padding_violation());\n\n')

    for p in scalar:
        n, w, count = p['name'], p['actual_width'], p['n_scalars']
        f.write(f'  wire [{w * count - 1}:0] {n}_flat;\n')
        f.write(f'  scalar_bank_mux #(.SCALAR_WIDTH({w}), .N_SCALARS({count}),\n')
        f.write(f'      .N_BANKS(N_BANKS), .BANK_ID_WIDTH(BANK_ID_WIDTH)) u_{n} (\n')
        f.write('      .ap_clk(ap_clk), .ap_rst(ap_rst), .cur_bank_id(cur_bank_id), .quiescent(quiescent),\n')
        f.write(f'      .ld_we(ld_{n}_we), .ld_bank(ld_{n}_bank), .ld_idx(ld_{n}_idx),\n')
        f.write(f'      .ld_data(ld_{n}_data), .ld_accept(ld_{n}_accept),\n')
        f.write(f'      .ld_reject(ld_{n}_reject), .q_flat({n}_flat));\n\n')

    conns = [
        '.ap_clk(ap_clk)',
        '.ap_rst(ap_rst)',
        '.ap_start(hls_ap_start)',
        '.ap_done(hls_ap_done)',
        '.ap_ready(hls_ap_ready)',
        '.ap_idle(hls_ap_idle)',
    ]
    for p in passthrough:
        conns.append(f'.{p["name"]}({p["name"]})')
    for p in bram:
        sig = p['actual_signals']
        # Both ports go to the IP as read ports; the bank lends port B to the
        # loader while quiescent. A layer that ignores port B just leaves EN_B low,
        # so this wiring is identical for every layer.
        for role in ('addr_a', 'en_a', 'din_a', 'dout_a', 'wen_a', 'clk_a', 'rst_a'):
            conns.append(f'.{sig[role]}({sig[role]})')
        for role in ('addr_b', 'en_b', 'dout_b'):
            conns.append(f'.{sig[role]}({sig[role]})')
        # the IP never writes the memory (interface.bram_is_read_only)
        for role in ('din_b', 'wen_b', 'clk_b', 'rst_b'):
            conns.append(f'.{sig[role]}()')
    for p in scalar:
        n, w = p['name'], p['actual_width']
        for i in range(p['n_scalars']):
            conns.append(f'.{n}_{i}({n}_flat[{w * i + w - 1}:{w * i}])')

    f.write(f'  // unmodified hls4ml IP\n  {project_name} u_{project_name} (\n')
    for i, c in enumerate(conns):
        f.write(f'      {c}' + (',\n' if i < len(conns) - 1 else '\n'))
    f.write('  );\n\nendmodule\n\n`default_nettype wire\n')


def _describe_banked_port(port):
    """Geometry keys are omitted for a scalar bundle, which has no memory."""
    entry = {
        'name': port['name'],
        'kind': port['expected_interface_kind'],
        'data_width': port.get('actual_data_width') or port.get('actual_width'),
        'n_scalars': port['n_scalars'],
    }
    if port['expected_interface_kind'] == 'bram':
        entry['depth'] = port['actual_depth']
        entry['bank_stride_words'] = _next_pow2(port['expected_depth'])
    return entry


def package(project, n_banks=2, output_dir=None):
    """Generate the banked-weight wrapper for a synthesized hls4ml project.

    Args:
        project: a ModelGraph, or the path to its output directory. Passing the
            model is preferred: the output directory and project name then come
            from it, rather than being guessed.
        n_banks: how many banks to provision. Fixed in the generated RTL; changing
            it means re-running this packager, not re-running HLS.
        output_dir: where to write the wrapper (default ``<project>/runtime_weights``).

    Returns a dict describing what was written, including a fingerprint of the
    exported IP.
    """
    project_dir = project.config.get_output_dir() if hasattr(project, 'config') else str(project)

    manifest_path = os.path.join(project_dir, 'firmware', 'weights', MANIFEST_FILENAME)
    if not os.path.exists(manifest_path):
        raise FileNotFoundError(
            f'no manifest at {manifest_path}; the project must be written with BramFactor set '
            'so that parameters are exposed outside the compute IP'
        )
    manifest = json.load(open(manifest_path))

    schema = manifest.get('schema')
    version = manifest.get('schema_version')
    if schema != EXPECTED_SCHEMA:
        raise ValueError(f'manifest schema is {schema!r}, expected {EXPECTED_SCHEMA!r}')
    if version not in SUPPORTED_SCHEMA_VERSIONS:
        raise ValueError(f'manifest schema version {version!r} is not one of {sorted(SUPPORTED_SCHEMA_VERSIONS)}')

    if manifest.get('backend') not in SUPPORTED_BACKENDS:
        raise ValueError(f'manifest backend is {manifest.get("backend")!r}, expected one of {sorted(SUPPORTED_BACKENDS)}')

    # hls4ml's output directory and project name are independent, so the directory
    # basename is not a usable default; the manifest is the only source.
    project_name = manifest.get('project_name')
    if not project_name:
        raise ValueError('manifest does not name a project')

    verified, hardware = interface.verify(manifest, project_dir, project_name)

    if hardware['control'] != REQUIRED_CONTROL_PROTOCOL:
        raise interface.InterfaceMismatch(
            f'control protocol is {hardware["control"]!r}; the idle-time wrapper requires {REQUIRED_CONTROL_PROTOCOL!r}'
        )
    unsupported = [p['name'] for p in manifest['ports'] if p['expected_interface_kind'] is None]
    if unsupported:
        raise InterfaceUnsupported(
            f'no verified adapter for external parameter(s) {unsupported}; banking only some of a '
            "model's parameters would leave the rest as unconnected top-level ports"
        )
    if not verified:
        raise ValueError('manifest describes no external parameters; nothing to bank')

    rtl_ports = interface.parse_rtl_ports(project_dir, project_name)

    # The loader shares port B with the IP, which is sound only if the IP never
    # writes the memory, so prove that from the exported RTL. Whether the IP reads
    # port B does not matter -- Dense leaves it idle, pointwise uses it.
    for port in verified:
        if port['expected_interface_kind'] != 'bram':
            continue
        signals = port['actual_signals']
        read_only, evidence = interface.bram_is_read_only(project_dir, project_name, signals)
        if not read_only:
            raise interface.InterfaceMismatch(
                f'{port["name"]}: the IP is not provably read-only on this memory ({evidence}); '
                'the loader cannot share a port with it'
            )
        # The wrapper clocks the banked memory with ap_clk and leaves Clk_A
        # dangling, which is only sound if the IP ties them together.
        same_clk, clk_evidence = interface.bram_port_clk_is_ap_clk(project_dir, project_name, signals)
        if not same_clk:
            raise interface.InterfaceMismatch(
                f'{port["name"]}: Clk_A is not provably tied to ap_clk ({clk_evidence}); '
                'the banked memory would be clocked by a different clock'
            )

    if n_banks < 2:
        raise ValueError('n_banks must be at least 2')
    bank_id_width = max(1, (n_banks - 1).bit_length())

    output_dir = output_dir or os.path.join(project_dir, 'runtime_weights')
    rtl_dir = os.path.join(output_dir, 'rtl')
    os.makedirs(rtl_dir, exist_ok=True)
    for module in STATIC_MODULES:
        shutil.copyfile(os.path.join(TEMPLATE_DIR, module), os.path.join(rtl_dir, module))

    # Vitis initializes generated ROMs with $readmemh("./<name>.dat"), resolved
    # against the simulator's or synthesizer's working directory. Vivado runs the
    # generated Tcl from output_dir, so the data has to be there too.
    hls_rtl_dir = interface.solution_verilog_dir(project_dir, project_name)
    rom_data = [n for n in sorted(os.listdir(hls_rtl_dir)) if n.endswith('.dat')]
    for name in rom_data:
        shutil.copyfile(os.path.join(hls_rtl_dir, name), os.path.join(output_dir, name))

    top_name = f'{project_name}_runtime_weights'
    with open(os.path.join(rtl_dir, f'{top_name}.sv'), 'w') as fh:
        _emit_top(fh, project_name, verified, rtl_ports, n_banks, bank_id_width, hardware['control'])

    with open(os.path.join(TEMPLATE_DIR, 'create_runtime_weights.tcl')) as fh:
        tcl = fh.read()
    tcl = (
        tcl.replace('@PROJECT_NAME@', project_name)
        .replace('@TOP_NAME@', top_name)
        .replace('@HLS_RTL_DIR@', os.path.abspath(hls_rtl_dir))
        .replace('@PART@', str(manifest['part']))
        .replace('@N_BANKS@', str(n_banks))
        .replace('@CLOCK_PERIOD@', str(manifest['clock_period']))
    )
    with open(os.path.join(output_dir, 'create_runtime_weights.tcl'), 'w') as fh:
        fh.write(tcl)

    summary = {
        'project_name': project_name,
        'top': top_name,
        'n_banks': n_banks,
        'bank_id_width': bank_id_width,
        'control_protocol': hardware['control'],
        'bank_selection': 'idle-time (bank committed before ap_start, held to ap_done)',
        'passthrough_ports': [p['name'] for p in _classify_ports(rtl_ports, verified)],
        'banked_ports': [_describe_banked_port(p) for p in verified],
        'rom_data_files': rom_data,
        'exported_ip_sha256': fingerprint_ip(project_dir, project_name),
    }
    with open(os.path.join(output_dir, 'runtime_weights.json'), 'w') as fh:
        json.dump(summary, fh, indent=2)
    return summary
