"""Post-export packaging: wrap an already-synthesized hls4ml IP with banked
parameter memories.

This runs AFTER ``build(synth=True)``. It only reads the generated project -- the
HLS compute IP is never modified, and its RTL stays byte-identical.

Not provided, by design: AXI or board support, any driver, a C++ wrapper, any
automatic change to ``BramFactor``, and any support for overlapping transactions.
Bank selection is idle-time only.
"""

import hashlib
import json
import os
import shutil

from hls4ml.contrib.runtime_weights import interface
from hls4ml.writer.external_parameters import MANIFEST_FILENAME

# Verified independently of the writer: if hls4ml starts emitting a different
# schema, packaging must fail loudly rather than misread the new semantics.
EXPECTED_SCHEMA = 'hls4ml.external_parameter_manifest/v1'
SUPPORTED_SCHEMA_VERSIONS = frozenset({1})

# Only the Vitis flow has been verified end to end. Note this is about which
# hls4ml backend produced the IP; Vivado is still used to implement the result.
SUPPORTED_BACKENDS = frozenset({'Vitis'})


class InterfaceUnsupported(Exception):
    """The model has an external parameter this version cannot bank."""


# The ownership latch drives ap_start/ap_ready directly, so anything else
# (ap_ctrl_chain, ap_ctrl_none) would be mis-driven rather than merely unsupported.
REQUIRED_CONTROL_PROTOCOL = 'ap_ctrl_hs'

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'templates')
STATIC_MODULES = ['bank_addr_mapper.sv', 'bank_select_latch.sv', 'parameter_bank.sv', 'scalar_bank_mux.sv']


def _next_pow2(n):
    return 1 << (n - 1).bit_length() if n > 1 else 1


def fingerprint_ip(project_dir, project_name):
    """SHA-256 over the exported RTL.

    This records the state of the IP; on its own it proves nothing about what the
    IP looked like earlier. Comparing a fingerprint taken before packaging with
    one taken after is what shows the IP was left alone.
    """
    verilog = os.path.join(project_dir, f'{project_name}_prj', 'solution1', 'syn', 'verilog')
    entries = []
    for name in sorted(os.listdir(verilog)):
        if name.endswith('.v'):
            digest = hashlib.sha256(open(os.path.join(verilog, name), 'rb').read()).hexdigest()
            entries.append(f'{digest}  {name}')
    combined = hashlib.sha256('\n'.join(entries).encode()).hexdigest()
    return {'combined': combined, 'files': entries}


# The bank count is fixed when the wrapper is generated: the packed memory image,
# runtime_weights.json and the bank stride all encode it, so an elaboration-time
# override would produce a design inconsistent with its own artifacts. Re-banking
# costs a packager run, not an HLS run. Both constants are emitted as localparams
# ahead of the port list so the ports can reference them.
CONTROL_PORTS = {'ap_clk', 'ap_rst', 'ap_start', 'ap_done', 'ap_ready', 'ap_idle'}
BRAM_SUFFIXES = [
    'Addr_A',
    'EN_A',
    'Din_A',
    'Dout_A',
    'WEN_A',
    'Clk_A',
    'Rst_A',
    'Addr_B',
    'EN_B',
    'Din_B',
    'Dout_B',
    'WEN_B',
    'Clk_B',
    'Rst_B',
]


def _classify_ports(rtl_ports, banked):
    """Split the IP's real port list into control / banked / pass-through."""
    bram_names = [p['name'] for p in banked if p['expected_interface_kind'] == 'bram']
    scalar_members = set()
    for p in banked:
        if p['expected_interface_kind'] == 'scalar_bundle':
            scalar_members.update(p['actual_ports'])

    owned = set(CONTROL_PORTS) | scalar_members
    for name in bram_names:
        owned.update(f'{name}_{suffix}' for suffix in BRAM_SUFFIXES)

    passthrough = [p for p in rtl_ports if p['name'] not in owned]
    return passthrough


def _decl(port, prefix=''):
    direction = 'input  wire' if port['dir'] == 'input' else 'output wire'
    width = '' if port['width'] == 1 else f'[{port["width"] - 1}:0] '
    return f'    {direction} {width}{prefix}{port["name"]}'


def _emit_top(f, project_name, banked, rtl_ports, n_banks, bank_id_width, control):
    """Generate the integration top.

    Every port of the wrapped IP is declared and connected explicitly: control to
    the ownership latch, banked parameters to their memories, and everything else
    (the network inputs and outputs) passed through to this module's own ports.
    No implicit .* connection is used -- it cannot resolve here, because the IP's
    data ports are not nets in this scope.
    """
    bram = [p for p in banked if p['expected_interface_kind'] == 'bram']
    scalar = [p for p in banked if p['expected_interface_kind'] == 'scalar_bundle']
    passthrough = _classify_ports(rtl_ports, banked)

    f.write('// GENERATED by hls4ml.contrib.runtime_weights -- do not edit.\n')
    f.write(f'// Wraps the unmodified {project_name} IP with runtime-selected weight banks.\n')
    f.write(f'// Control protocol: {control}. Bank selection is idle-time only.\n\n')
    f.write('`timescale 1 ns / 1 ps\n')
    f.write('`default_nettype none\n\n')
    f.write(f'module {project_name}_runtime_weights #(\n')
    init_params = [f'    parameter {p["name"].upper()}_INIT_HEX = ""' for p in bram]
    f.write(',\n'.join(init_params) if init_params else '    parameter UNUSED = 0')
    f.write('\n) (\n')

    lines = [
        '    input  wire ap_clk',
        '    input  wire ap_rst',
        '',
        '    // transaction boundary',
        '    input  wire ext_ap_start',
        f'    input  wire [{bank_id_width - 1}:0] ext_bank_id',
        '    output wire ext_ap_ready',
        '    output wire ext_ap_done',
        '    output wire ext_bank_id_bad',
        '',
    ]
    if passthrough:
        lines.append('    // network data ports, passed through to the IP')
        lines.extend(_decl(p) for p in passthrough)
        lines.append('')
    lines.append('    // loader (accepted only while idle)')
    for p in bram:
        n = p['name']
        word_bits = max((p['expected_depth'] - 1).bit_length(), 1)
        lines += [
            f'    input  wire ld_{n}_req',
            f'    input  wire [{bank_id_width - 1}:0] ld_{n}_bank',
            f'    input  wire [{word_bits - 1}:0] ld_{n}_word',
            f'    input  wire [{p["actual_data_width"] - 1}:0] ld_{n}_wdata',
            f'    output wire ld_{n}_accept',
            f'    output wire ld_{n}_reject',
        ]
    for p in scalar:
        n = p['name']
        idx_bits = max((p['n_scalars'] - 1).bit_length(), 1)
        lines += [
            f'    input  wire ld_{n}_we',
            f'    input  wire [{bank_id_width - 1}:0] ld_{n}_bank',
            f'    input  wire [{idx_bits - 1}:0] ld_{n}_idx',
            f'    input  wire [{p["actual_width"] - 1}:0] ld_{n}_data',
            f'    output wire ld_{n}_accept',
            f'    output wire ld_{n}_reject',
        ]
    lines += [
        '',
        '    // observability',
        f'    output wire [{bank_id_width - 1}:0] cur_bank_id',
        '    output wire busy',
        '    output wire quiescent',
    ]

    body = [ln for ln in lines if ln.strip()]
    for ln in lines:
        if not ln.strip():
            f.write('\n')
        else:
            last = ln is body[-1]
            f.write(ln + ('\n' if last else ',\n'))
    f.write(');\n\n')

    f.write(f'  localparam int N_BANKS       = {n_banks};\n')
    f.write(f'  localparam int BANK_ID_WIDTH = {bank_id_width};\n\n')
    f.write('  wire hls_ap_start, hls_ap_done, hls_ap_idle, hls_ap_ready;\n\n')
    f.write('  bank_select_latch #(.BANK_ID_WIDTH(BANK_ID_WIDTH), .N_BANKS(N_BANKS)) u_latch (\n')
    f.write('      .ap_clk(ap_clk), .ap_rst(ap_rst),\n')
    f.write('      .ext_ap_start(ext_ap_start), .ext_bank_id(ext_bank_id),\n')
    f.write('      .ext_ap_ready(ext_ap_ready), .ext_bank_id_bad(ext_bank_id_bad),\n')
    f.write('      .hls_ap_start(hls_ap_start), .hls_ap_ready(hls_ap_ready),\n')
    f.write('      .hls_ap_idle(hls_ap_idle), .hls_ap_done(hls_ap_done),\n')
    f.write('      .cur_bank_id(cur_bank_id), .busy(busy), .quiescent(quiescent));\n\n')
    f.write('  assign ext_ap_done = hls_ap_done;\n\n')

    for p in bram:
        n, dw = p['name'], p['actual_data_width']
        stride = _next_pow2(p['expected_depth'])
        f.write(f'  wire [{p["actual_addr_width"] - 1}:0] {n}_Addr_A;\n')
        f.write(f'  wire {n}_EN_A, {n}_Clk_A, {n}_Rst_A;\n')
        f.write(f'  wire [{dw - 1}:0] {n}_Din_A, {n}_Dout_A;\n')
        f.write(f'  wire [{dw // 8 - 1}:0] {n}_WEN_A;\n')
        f.write(f'  parameter_bank #(.DATA_WIDTH({dw}), .HLS_ADDR_WIDTH({p["actual_addr_width"]}),\n')
        f.write(f'      .WORD_BYTES({p["actual_word_bytes"]}), .LOCAL_WORDS({p["expected_depth"]}),\n')
        f.write('      .N_BANKS(N_BANKS), .BANK_ID_WIDTH(BANK_ID_WIDTH),\n')
        f.write(f'      .BANK_STRIDE_WORDS({stride}), .INIT_HEX({n.upper()}_INIT_HEX)) u_{n} (\n')
        f.write('      .ap_clk(ap_clk), .ap_rst(ap_rst), .cur_bank_id(cur_bank_id), .quiescent(quiescent),\n')
        f.write(f'      .hls_Addr_A({n}_Addr_A), .hls_EN_A({n}_EN_A), .hls_WEN_A({n}_WEN_A),\n')
        f.write(f'      .hls_Din_A({n}_Din_A), .hls_Dout_A({n}_Dout_A), .hls_Rst_A({n}_Rst_A),\n')
        f.write(f'      .ld_req(ld_{n}_req), .ld_bank(ld_{n}_bank), .ld_word(ld_{n}_word),\n')
        f.write(f'      .ld_wdata(ld_{n}_wdata),\n')
        f.write(f'      .ld_accept(ld_{n}_accept), .ld_reject(ld_{n}_reject),\n')
        f.write('      .addr_padding_violation());\n\n')

    for p in scalar:
        n, w, count = p['name'], p['actual_width'], p['n_scalars']
        f.write(f'  wire [{w * count - 1}:0] {n}_flat;\n')
        f.write(f'  scalar_bank_mux #(.SCALAR_WIDTH({w}), .N_SCALARS({count}),\n')
        f.write(f'      .N_BANKS(N_BANKS), .BANK_ID_WIDTH(BANK_ID_WIDTH)) u_{n} (\n')
        f.write('      .ap_clk(ap_clk), .ap_rst(ap_rst), .cur_bank_id(cur_bank_id), .quiescent(quiescent),\n')
        f.write(f'      .ld_we(ld_{n}_we), .ld_bank(ld_{n}_bank), .ld_idx(ld_{n}_idx),\n')
        f.write(f'      .ld_data(ld_{n}_data), .ld_accept(ld_{n}_accept),\n')
        f.write(f'      .ld_reject(ld_{n}_reject), .q_flat({n}_flat));\n\n')

    conns = [
        '.ap_clk(ap_clk)',
        '.ap_rst(ap_rst)',
        '.ap_start(hls_ap_start)',
        '.ap_done(hls_ap_done)',
        '.ap_ready(hls_ap_ready)',
        '.ap_idle(hls_ap_idle)',
    ]
    for p in passthrough:
        conns.append(f'.{p["name"]}({p["name"]})')
    for p in bram:
        n, dw = p['name'], p['actual_data_width']
        for suffix in ('Addr_A', 'EN_A', 'Din_A', 'Dout_A', 'WEN_A', 'Clk_A', 'Rst_A'):
            conns.append(f'.{n}_{suffix}({n}_{suffix})')
        # port B is proven unused by the IP (interface.bram_port_b_is_unused)
        for suffix in ('Addr_B', 'EN_B', 'Din_B', 'WEN_B', 'Clk_B', 'Rst_B'):
            conns.append(f'.{n}_{suffix}()')
        conns.append(f".{n}_Dout_B({{{dw}{{1'b0}}}})")
    for p in scalar:
        n, w = p['name'], p['actual_width']
        for i in range(p['n_scalars']):
            conns.append(f'.{n}_{i}({n}_flat[{w * i + w - 1}:{w * i}])')

    f.write(f'  // unmodified hls4ml IP\n  {project_name} u_{project_name} (\n')
    for i, c in enumerate(conns):
        f.write(f'      {c}' + (',\n' if i < len(conns) - 1 else '\n'))
    f.write('  );\n\nendmodule\n\n`default_nettype wire\n')


def package(project, n_banks=2, output_dir=None, project_name=None):
    """Generate the banked-weight wrapper for a synthesized hls4ml project.

    Args:
        project: a ModelGraph, or the path to its output directory. Passing the
            model is preferred: the output directory and project name then come
            from it, rather than being guessed.
        n_banks: how many banks to provision. Fixed in the generated RTL; changing
            it means re-running this packager, not re-running HLS.
        output_dir: where to write the wrapper (default ``<project>/runtime_weights``).
        project_name: only needed when ``project`` is a path and the manifest is
            somehow unavailable; normally taken from the manifest.

    Returns a dict describing what was written, including a fingerprint of the
    exported IP.
    """
    if hasattr(project, 'config'):  # a ModelGraph
        project_dir = project.config.get_output_dir()
        project_name = project_name or project.config.get_project_name()
    else:
        project_dir = str(project)

    manifest_path = os.path.join(project_dir, 'firmware', 'weights', MANIFEST_FILENAME)
    if not os.path.exists(manifest_path):
        raise FileNotFoundError(
            f'no manifest at {manifest_path}; the project must be written with BramFactor set '
            'so that parameters are exposed outside the compute IP'
        )
    manifest = json.load(open(manifest_path))

    schema = manifest.get('schema')
    version = manifest.get('schema_version')
    if schema != EXPECTED_SCHEMA:
        raise ValueError(f'manifest schema is {schema!r}, expected {EXPECTED_SCHEMA!r}')
    if version not in SUPPORTED_SCHEMA_VERSIONS:
        raise ValueError(f'manifest schema version {version!r} is not one of {sorted(SUPPORTED_SCHEMA_VERSIONS)}')

    if manifest.get('backend') not in SUPPORTED_BACKENDS:
        raise ValueError(f'manifest backend is {manifest.get("backend")!r}, expected one of {sorted(SUPPORTED_BACKENDS)}')

    # hls4ml's output directory and project name are independent, so the
    # directory basename is not a usable default. Take it from the manifest.
    if project_name is None:
        project_name = manifest.get('project_name')
    elif manifest.get('project_name') != project_name:
        raise ValueError(f'manifest is for project {manifest.get("project_name")!r}, not {project_name!r}')
    if not project_name:
        raise ValueError('manifest does not name a project')

    verified, hardware = interface.verify(manifest, project_dir, project_name)

    if hardware['control'] != REQUIRED_CONTROL_PROTOCOL:
        raise interface.InterfaceMismatch(
            f'control protocol is {hardware["control"]!r}; the idle-time wrapper requires {REQUIRED_CONTROL_PROTOCOL!r}'
        )
    unsupported = [p['name'] for p in manifest['ports'] if p['expected_interface_kind'] is None]
    if unsupported:
        raise InterfaceUnsupported(
            f'no verified adapter for external parameter(s) {unsupported}; banking only some of a '
            "model's parameters would leave the rest as unconnected top-level ports"
        )
    if not verified:
        raise ValueError('manifest describes no external parameters; nothing to bank')

    rtl_ports = interface.parse_rtl_ports(project_dir, project_name)

    # The loader borrows port B of each BRAM interface. That is only sound if the
    # IP really leaves it idle, so prove it from the exported RTL.
    for port in verified:
        if port['expected_interface_kind'] != 'bram':
            continue
        unused, evidence = interface.bram_port_b_is_unused(project_dir, project_name, port['name'])
        if not unused:
            raise interface.InterfaceMismatch(
                f'{port["name"]}: port B is not provably unused by the IP ({evidence}); the loader cannot borrow it'
            )
        # The wrapper clocks the banked memory with ap_clk and leaves Clk_A
        # dangling, which is only sound if the IP ties them together.
        same_clk, clk_evidence = interface.bram_port_clk_is_ap_clk(project_dir, project_name, port['name'])
        if not same_clk:
            raise interface.InterfaceMismatch(
                f'{port["name"]}: Clk_A is not provably tied to ap_clk ({clk_evidence}); '
                'the banked memory would be clocked by a different clock'
            )

    if n_banks < 2:
        raise ValueError('n_banks must be at least 2')
    bank_id_width = max(1, (n_banks - 1).bit_length())

    output_dir = output_dir or os.path.join(project_dir, 'runtime_weights')
    rtl_dir = os.path.join(output_dir, 'rtl')
    os.makedirs(rtl_dir, exist_ok=True)
    for module in STATIC_MODULES:
        shutil.copyfile(os.path.join(TEMPLATE_DIR, module), os.path.join(rtl_dir, module))

    top_name = f'{project_name}_runtime_weights'
    with open(os.path.join(rtl_dir, f'{top_name}.sv'), 'w') as fh:
        _emit_top(fh, project_name, verified, rtl_ports, n_banks, bank_id_width, hardware['control'])

    with open(os.path.join(TEMPLATE_DIR, 'create_runtime_weights.tcl')) as fh:
        tcl = fh.read()
    tcl = (
        tcl.replace('@PROJECT_NAME@', project_name)
        .replace('@TOP_NAME@', top_name)
        .replace('@PART@', str(manifest['part']))
        .replace('@N_BANKS@', str(n_banks))
        .replace('@CLOCK_PERIOD@', str(manifest['clock_period']))
    )
    with open(os.path.join(output_dir, 'create_runtime_weights.tcl'), 'w') as fh:
        fh.write(tcl)

    summary = {
        'project_name': project_name,
        'top': top_name,
        'n_banks': n_banks,
        'bank_id_width': bank_id_width,
        'control_protocol': hardware['control'],
        'bank_selection': 'idle-time (bank committed before ap_start, held to ap_done)',
        'port_b_verified_unused': True,
        'port_clk_verified_ap_clk': True,
        'passthrough_ports': [p['name'] for p in _classify_ports(rtl_ports, verified)],
        'banked_ports': [
            {
                'name': p['name'],
                'kind': p['expected_interface_kind'],
                'data_width': p.get('actual_data_width') or p.get('actual_width'),
                'depth': p.get('actual_depth'),
                'word_bytes': p.get('actual_word_bytes'),
                'bank_stride_words': _next_pow2(p['expected_depth']) if p['expected_depth'] else None,
                'n_scalars': p['n_scalars'],
            }
            for p in verified
        ],
        'exported_ip_sha256': fingerprint_ip(project_dir, project_name),
    }
    with open(os.path.join(output_dir, 'runtime_weights.json'), 'w') as fh:
        json.dump(summary, fh, indent=2)
    return summary
