#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import print_function

__version__ = '0.2.0'

import argparse
import os
import re
import sys
import yaml
import json
import h5py
import hls4ml

from shutil import copyfile

config_filename = 'hls4ml_config.yml'

def parse_config(config_file):
    print('Loading configuration from', config_file)
    config = open(config_file, 'r')
    return yaml.load(config, Loader=yaml.SafeLoader)

def main():
    parser = argparse.ArgumentParser(description='HLS4ML - Machine learning inference in FPGAs')
    subparsers = parser.add_subparsers()

    config_parser = subparsers.add_parser('config', help='Create a conversion configuration file')
    convert_parser = subparsers.add_parser('convert', help='Convert Keras or ONNX model to HLS')
    build_parser = subparsers.add_parser('build', help='Build generated HLS project')
    report_parser = subparsers.add_parser('report', help='Show synthesis report of an HLS project')

    config_parser.add_argument('-m', '--model', help='Model file to convert (Keras .h5 or .json file, ONNX .onnx file, or TensorFlow .pb file)', default=None)
    config_parser.add_argument('-w', '--weights', help='Optional weights file (if Keras .json file is provided))', default=None)
    config_parser.add_argument('-p', '--project', help='Project name', default='myproject')
    config_parser.add_argument('-d', '--dir', help='Project output directory', default='my-hls-test')
    config_parser.add_argument('-b', '--backend', help='Backend : Vivado (Xilinx) / Quartus (Intel)', default='Vivado')
    config_parser.add_argument('-f', '--fpga', help='FPGA part', default='xcku115-flvb2104-2-i')
    config_parser.add_argument('-c', '--clock', help='Clock frequency (ns)', type=int, default=5)
    config_parser.add_argument('-g', '--granularity', help='Granularity of configuration. One of "model", "type" or "name"', default='model')
    config_parser.add_argument('-x', '--precision', help='Default precision <Total Bits, Integer Bits, SIGNED/UNSIGNED, Quantization Mode (Optional), Saturation Mode (Optional), Saturation Bits (Optional)> ex: <16,6,UNSIGNED> or <16,6> or <16>', default='<16,6>')
    config_parser.add_argument('-r', '--reuse-factor', help='Default reuse factor', type=int, default=1)
    config_parser.add_argument('-o', '--output', help='Output file name', default=None)
    config_parser.set_defaults(func=config)

    convert_parser.add_argument('-c', '--config', help='Configuration file', default=None)
    convert_parser.set_defaults(func=convert)

    build_parser.add_argument('-p', '--project', help='Project directory', default=None)
    build_parser.add_argument('-c', '--simulation', help='Run C simulation', action='store_true', default=False)
    build_parser.add_argument('-s', '--synthesis', help='Run C/RTL synthesis', action='store_true', default=False)
    build_parser.add_argument('-r', '--co-simulation', help='Run C/RTL co-simulation', action='store_true', default=False)
    build_parser.add_argument('-v', '--validation', help='Run C/RTL validation', action='store_true', default=False)
    build_parser.add_argument('-e', '--export', help='Export IP (implies -s)', action='store_true', default=False)
    build_parser.add_argument('-l', '--fpga-synthesis', help='Run Vivado/Quartus synthesis (implies -s)', action='store_true', default=False)
    build_parser.add_argument('-a', '--all', help='Run C simulation, C/RTL synthesis, C/RTL co-simulation and Vivado synthesis', action='store_true')
    build_parser.add_argument('--reset', help='Remove any previous builds', action='store_true', default=False)
    build_parser.set_defaults(func=build)

    report_parser.add_argument('-p', '--project', help='Project directory', default=None)
    report_parser.add_argument('-f', '--full', help='Show full report', action='store_true', default=False)
    report_parser.add_argument('-b', '--browser', help='Open a browser for the report (if supported)', action='store_true', default=False)
    report_parser.set_defaults(func=report)

    parser.add_argument('--version', action='version', version='%(prog)s {version}'.format(version=__version__))

    args = parser.parse_args()
    if hasattr(args, 'func'):
        args.func(args)
    else:
        parser.print_usage()

def config(args):
    if args.model is None:
        print('Model file (-m or --model) must be provided.')
        sys.exit(1)

    config = hls4ml.utils.config.create_config(
        output_dir=args.dir,
        project_name=args.project,
        backend=args.backend,
        fpga_part=args.fpga,
        clock_period=args.clock
    )
    backend = hls4ml.templates.get_backend(args.backend)

    if args.model.endswith('.h5'):
        config['KerasH5'] = args.model

        with h5py.File(args.model, mode='r') as h5file:
            # Load the configuration from h5 using json's decode
            model_arch = h5file.attrs.get('model_config')
            if model_arch is None:
                print('No model found in the provided h5 file.')
                sys.exit(1)
            else:
                model_arch = json.loads(model_arch.decode('utf-8'))

            config['HLSConfig'] = hls4ml.utils.config_from_keras_model(
                model_arch,
                backend=backend,
                granularity=args.granularity,
                default_precision=args.precision,
                default_reuse_factor=args.reuse_factor
            )
    elif args.model.endswith('.json'):
        if args.weights is None:
            print('Weights file (-w or --weights) must be provided when parsing from JSON file.')
            sys.exit(1)
        config['KerasJson'] = args.model
        config['KerasH5'] = args.weights

        with open(args.model) as json_file:
            model_arch = json.load(json_file)
            config['HLSConfig'] = hls4ml.utils.config_from_keras_model(
                model_arch,
                backend=backend,
                granularity=args.granularity,
                default_precision=args.precision,
                default_reuse_factor=args.reuse_factor
            )
    elif args.model.endswith('.onnx'):
        print('Creating configuration for ONNX models is not supported yet.')
        sys.exit(1)
    elif args.model.endswith('.pb'):
        print('Creating configuration for Tensorflow models is not supported yet.')
        sys.exit(1)

    if args.output is not None:
        outname = args.output
        if not outname.endswith('.yml'):
            outname += '.yml'
        print('Writing config to {}'.format(outname))
        with open(outname, 'w') as outfile:
            yaml.dump(config, outfile, default_flow_style=False, sort_keys=False)
    else:
        print('Config output:')
        yaml.dump(config, sys.stdout, default_flow_style=False, sort_keys=False)

def convert(args):
    yamlConfig = parse_config(args.config)
    print('Using Backend:', yamlConfig['Backend'])
    model = hls4ml.converters.convert_from_yaml_config(yamlConfig)

    if model is not None:
        model.write()

    # Copy the config file to the generated folder
    copyfile(args.config, yamlConfig['OutputDir'] + '/' + config_filename)

def build(args):
    if args.project is None:
        print('Project directory (-p or --project) must be provided.')
        sys.exit(1)

    reset = int(args.reset)
    csim = int(args.simulation)
    synth = int(args.synthesis)
    cosim = int(args.co_simulation)
    validation = int(args.validation)
    export = int(args.export)
    fpgasynth = int(args.fpga_synthesis)
    if args.all:
        csim = synth = cosim = validation = export = fpgasynth = 1

    yamlConfig = parse_config(args.project + '/' + config_filename)

    # Check if vivado_hls is available
    if 'linux' in sys.platform or 'darwin' in sys.platform:
        backend = hls4ml.templates.get_backend(yamlConfig.get('Backend', 'Vivado'))
        if yamlConfig.get('Backend', 'Vivado') in hls4ml.templates.templates.backend_map:
            backend.build(dir=args.project, prj_config=yamlConfig, reset=reset, csim=csim, synth=synth, cosim=cosim, validation=validation, export=export, fpgasynth=fpgasynth)
        else:
            print('Backend not Implemented try [Vivado, Quartus]')
            sys.exit(2)

def report(args):
    if args.project is None:
        print('Project directory (-p or --project) must be provided.')
        sys.exit(1)

    yamlConfig = parse_config(args.project + '/' + config_filename)
    backend = hls4ml.templates.get_backend(yamlConfig.get('Backend', 'Vivado'))
    if yamlConfig.get('Backend', 'Vivado') in hls4ml.templates.templates.backend_map:
        backend.read_report(args.project, yamlConfig, args.full, args.browser)
    else:
        raise Exception('Backend not Implemented try [Vivado, Quartus]')

if __name__== "__main__":
    main()
