// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11
);


output   ap_ready;
input  [31:0] data_0_V_read;
input  [31:0] data_1_V_read;
input  [31:0] data_2_V_read;
input  [31:0] data_3_V_read;
input  [31:0] data_4_V_read;
input  [31:0] data_5_V_read;
input  [31:0] data_6_V_read;
input  [31:0] data_7_V_read;
input  [31:0] data_8_V_read;
input  [31:0] data_9_V_read;
input  [31:0] data_10_V_read;
input  [31:0] data_11_V_read;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;

wire   [0:0] tmp_29_fu_118_p2;
wire   [30:0] tmp_257_fu_124_p1;
wire   [30:0] res_0_V_write_assig_fu_128_p3;
wire   [0:0] tmp_29_1_fu_140_p2;
wire   [30:0] tmp_258_fu_146_p1;
wire   [30:0] res_1_V_write_assig_fu_150_p3;
wire   [0:0] tmp_29_2_fu_162_p2;
wire   [30:0] tmp_259_fu_168_p1;
wire   [30:0] res_2_V_write_assig_fu_172_p3;
wire   [0:0] tmp_29_3_fu_184_p2;
wire   [30:0] tmp_260_fu_190_p1;
wire   [30:0] res_3_V_write_assig_fu_194_p3;
wire   [0:0] tmp_29_4_fu_206_p2;
wire   [30:0] tmp_261_fu_212_p1;
wire   [30:0] res_4_V_write_assig_fu_216_p3;
wire   [0:0] tmp_29_5_fu_228_p2;
wire   [30:0] tmp_262_fu_234_p1;
wire   [30:0] res_5_V_write_assig_fu_238_p3;
wire   [0:0] tmp_29_6_fu_250_p2;
wire   [30:0] tmp_263_fu_256_p1;
wire   [30:0] res_6_V_write_assig_fu_260_p3;
wire   [0:0] tmp_29_7_fu_272_p2;
wire   [30:0] tmp_264_fu_278_p1;
wire   [30:0] res_7_V_write_assig_fu_282_p3;
wire   [0:0] tmp_29_8_fu_294_p2;
wire   [30:0] tmp_265_fu_300_p1;
wire   [30:0] res_8_V_write_assig_fu_304_p3;
wire   [0:0] tmp_29_9_fu_316_p2;
wire   [30:0] tmp_266_fu_322_p1;
wire   [30:0] res_9_V_write_assig_fu_326_p3;
wire   [0:0] tmp_29_s_fu_338_p2;
wire   [30:0] tmp_267_fu_344_p1;
wire   [30:0] res_10_V_write_assi_fu_348_p3;
wire   [0:0] tmp_29_10_fu_360_p2;
wire   [30:0] tmp_268_fu_366_p1;
wire   [30:0] res_11_V_write_assi_fu_370_p3;
wire   [31:0] res_0_V_write_assig_1_fu_136_p1;
wire   [31:0] res_1_V_write_assig_1_fu_158_p1;
wire   [31:0] res_2_V_write_assig_1_fu_180_p1;
wire   [31:0] res_3_V_write_assig_1_fu_202_p1;
wire   [31:0] res_4_V_write_assig_1_fu_224_p1;
wire   [31:0] res_5_V_write_assig_1_fu_246_p1;
wire   [31:0] res_6_V_write_assig_1_fu_268_p1;
wire   [31:0] res_7_V_write_assig_1_fu_290_p1;
wire   [31:0] res_8_V_write_assig_1_fu_312_p1;
wire   [31:0] res_9_V_write_assig_1_fu_334_p1;
wire   [31:0] res_10_V_write_assi_1_fu_356_p1;
wire   [31:0] res_11_V_write_assi_1_fu_378_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = res_0_V_write_assig_1_fu_136_p1;

assign ap_return_1 = res_1_V_write_assig_1_fu_158_p1;

assign ap_return_10 = res_10_V_write_assi_1_fu_356_p1;

assign ap_return_11 = res_11_V_write_assi_1_fu_378_p1;

assign ap_return_2 = res_2_V_write_assig_1_fu_180_p1;

assign ap_return_3 = res_3_V_write_assig_1_fu_202_p1;

assign ap_return_4 = res_4_V_write_assig_1_fu_224_p1;

assign ap_return_5 = res_5_V_write_assig_1_fu_246_p1;

assign ap_return_6 = res_6_V_write_assig_1_fu_268_p1;

assign ap_return_7 = res_7_V_write_assig_1_fu_290_p1;

assign ap_return_8 = res_8_V_write_assig_1_fu_312_p1;

assign ap_return_9 = res_9_V_write_assig_1_fu_334_p1;

assign res_0_V_write_assig_1_fu_136_p1 = res_0_V_write_assig_fu_128_p3;

assign res_0_V_write_assig_fu_128_p3 = ((tmp_29_fu_118_p2[0:0] === 1'b1) ? tmp_257_fu_124_p1 : 31'd0);

assign res_10_V_write_assi_1_fu_356_p1 = res_10_V_write_assi_fu_348_p3;

assign res_10_V_write_assi_fu_348_p3 = ((tmp_29_s_fu_338_p2[0:0] === 1'b1) ? tmp_267_fu_344_p1 : 31'd0);

assign res_11_V_write_assi_1_fu_378_p1 = res_11_V_write_assi_fu_370_p3;

assign res_11_V_write_assi_fu_370_p3 = ((tmp_29_10_fu_360_p2[0:0] === 1'b1) ? tmp_268_fu_366_p1 : 31'd0);

assign res_1_V_write_assig_1_fu_158_p1 = res_1_V_write_assig_fu_150_p3;

assign res_1_V_write_assig_fu_150_p3 = ((tmp_29_1_fu_140_p2[0:0] === 1'b1) ? tmp_258_fu_146_p1 : 31'd0);

assign res_2_V_write_assig_1_fu_180_p1 = res_2_V_write_assig_fu_172_p3;

assign res_2_V_write_assig_fu_172_p3 = ((tmp_29_2_fu_162_p2[0:0] === 1'b1) ? tmp_259_fu_168_p1 : 31'd0);

assign res_3_V_write_assig_1_fu_202_p1 = res_3_V_write_assig_fu_194_p3;

assign res_3_V_write_assig_fu_194_p3 = ((tmp_29_3_fu_184_p2[0:0] === 1'b1) ? tmp_260_fu_190_p1 : 31'd0);

assign res_4_V_write_assig_1_fu_224_p1 = res_4_V_write_assig_fu_216_p3;

assign res_4_V_write_assig_fu_216_p3 = ((tmp_29_4_fu_206_p2[0:0] === 1'b1) ? tmp_261_fu_212_p1 : 31'd0);

assign res_5_V_write_assig_1_fu_246_p1 = res_5_V_write_assig_fu_238_p3;

assign res_5_V_write_assig_fu_238_p3 = ((tmp_29_5_fu_228_p2[0:0] === 1'b1) ? tmp_262_fu_234_p1 : 31'd0);

assign res_6_V_write_assig_1_fu_268_p1 = res_6_V_write_assig_fu_260_p3;

assign res_6_V_write_assig_fu_260_p3 = ((tmp_29_6_fu_250_p2[0:0] === 1'b1) ? tmp_263_fu_256_p1 : 31'd0);

assign res_7_V_write_assig_1_fu_290_p1 = res_7_V_write_assig_fu_282_p3;

assign res_7_V_write_assig_fu_282_p3 = ((tmp_29_7_fu_272_p2[0:0] === 1'b1) ? tmp_264_fu_278_p1 : 31'd0);

assign res_8_V_write_assig_1_fu_312_p1 = res_8_V_write_assig_fu_304_p3;

assign res_8_V_write_assig_fu_304_p3 = ((tmp_29_8_fu_294_p2[0:0] === 1'b1) ? tmp_265_fu_300_p1 : 31'd0);

assign res_9_V_write_assig_1_fu_334_p1 = res_9_V_write_assig_fu_326_p3;

assign res_9_V_write_assig_fu_326_p3 = ((tmp_29_9_fu_316_p2[0:0] === 1'b1) ? tmp_266_fu_322_p1 : 31'd0);

assign tmp_257_fu_124_p1 = data_0_V_read[30:0];

assign tmp_258_fu_146_p1 = data_1_V_read[30:0];

assign tmp_259_fu_168_p1 = data_2_V_read[30:0];

assign tmp_260_fu_190_p1 = data_3_V_read[30:0];

assign tmp_261_fu_212_p1 = data_4_V_read[30:0];

assign tmp_262_fu_234_p1 = data_5_V_read[30:0];

assign tmp_263_fu_256_p1 = data_6_V_read[30:0];

assign tmp_264_fu_278_p1 = data_7_V_read[30:0];

assign tmp_265_fu_300_p1 = data_8_V_read[30:0];

assign tmp_266_fu_322_p1 = data_9_V_read[30:0];

assign tmp_267_fu_344_p1 = data_10_V_read[30:0];

assign tmp_268_fu_366_p1 = data_11_V_read[30:0];

assign tmp_29_10_fu_360_p2 = (($signed(data_11_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_1_fu_140_p2 = (($signed(data_1_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_2_fu_162_p2 = (($signed(data_2_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_3_fu_184_p2 = (($signed(data_3_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_4_fu_206_p2 = (($signed(data_4_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_5_fu_228_p2 = (($signed(data_5_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_6_fu_250_p2 = (($signed(data_6_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_7_fu_272_p2 = (($signed(data_7_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_8_fu_294_p2 = (($signed(data_8_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_9_fu_316_p2 = (($signed(data_9_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_fu_118_p2 = (($signed(data_0_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_29_s_fu_338_p2 = (($signed(data_10_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

endmodule //relu
