// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "compute_layer_0_0_0_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic compute_layer_0_0_0_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic compute_layer_0_0_0_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> compute_layer_0_0_0_1::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<2> compute_layer_0_0_0_1::ap_ST_fsm_pp0_stage1 = "10";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> compute_layer_0_0_0_1::ap_const_lv1_1 = "1";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_1 = "1";
const sc_lv<28> compute_layer_0_0_0_1::ap_const_lv28_FFFFED4 = "1111111111111111111011010100";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_7FFFF71 = "111111111111111111101110001";
const sc_lv<26> compute_layer_0_0_0_1::ap_const_lv26_5C = "1011100";
const sc_lv<26> compute_layer_0_0_0_1::ap_const_lv26_3FFFF97 = "11111111111111111110010111";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_7FFFF52 = "111111111111111111101010010";
const sc_lv<28> compute_layer_0_0_0_1::ap_const_lv28_FFFFEB3 = "1111111111111111111010110011";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_7FFFF4B = "111111111111111111101001011";
const sc_lv<28> compute_layer_0_0_0_1::ap_const_lv28_FFFFE87 = "1111111111111111111010000111";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_F2 = "11110010";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_7FFFF46 = "111111111111111111101000110";
const sc_lv<28> compute_layer_0_0_0_1::ap_const_lv28_FFFFE4A = "1111111111111111111001001010";
const sc_lv<28> compute_layer_0_0_0_1::ap_const_lv28_FFFFEB6 = "1111111111111111111010110110";
const sc_lv<28> compute_layer_0_0_0_1::ap_const_lv28_FFFFE92 = "1111111111111111111010010010";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_7FFFF5C = "111111111111111111101011100";
const sc_lv<24> compute_layer_0_0_0_1::ap_const_lv24_19 = "11001";
const sc_lv<24> compute_layer_0_0_0_1::ap_const_lv24_1D = "11101";
const sc_lv<25> compute_layer_0_0_0_1::ap_const_lv25_32 = "110010";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_9F = "10011111";
const sc_lv<28> compute_layer_0_0_0_1::ap_const_lv28_FFFFE73 = "1111111111111111111001110011";
const sc_lv<26> compute_layer_0_0_0_1::ap_const_lv26_3FFFF9F = "11111111111111111110011111";
const sc_lv<26> compute_layer_0_0_0_1::ap_const_lv26_4A = "1001010";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_7FFFF0B = "111111111111111111100001011";
const sc_lv<27> compute_layer_0_0_0_1::ap_const_lv27_BF = "10111111";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_A = "1010";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_1A = "11010";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_19 = "11001";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_17 = "10111";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_1B = "11011";
const sc_lv<6> compute_layer_0_0_0_1::ap_const_lv6_0 = "000000";
const sc_lv<2> compute_layer_0_0_0_1::ap_const_lv2_0 = "00";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_18 = "11000";
const sc_lv<1> compute_layer_0_0_0_1::ap_const_lv1_0 = "0";
const sc_lv<7> compute_layer_0_0_0_1::ap_const_lv7_0 = "0000000";
const sc_lv<5> compute_layer_0_0_0_1::ap_const_lv5_0 = "00000";
const sc_lv<21> compute_layer_0_0_0_1::ap_const_lv21_0 = "000000000000000000000";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_14 = "10100";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_3 = "11";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_11 = "10001";
const sc_lv<3> compute_layer_0_0_0_1::ap_const_lv3_0 = "000";
const sc_lv<22> compute_layer_0_0_0_1::ap_const_lv22_0 = "0000000000000000000000";
const sc_lv<32> compute_layer_0_0_0_1::ap_const_lv32_15 = "10101";
const sc_lv<9> compute_layer_0_0_0_1::ap_const_lv9_0 = "000000000";
const sc_lv<16> compute_layer_0_0_0_1::ap_const_lv16_FF86 = "1111111110000110";

compute_layer_0_0_0_1::compute_layer_0_0_0_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_mul_18seOg_x_U127 = new myproject_mul_18seOg<1,3,18,10,28>("myproject_mul_18seOg_x_U127");
    myproject_mul_18seOg_x_U127->clk(ap_clk);
    myproject_mul_18seOg_x_U127->reset(ap_rst);
    myproject_mul_18seOg_x_U127->din0(data_23_V_read);
    myproject_mul_18seOg_x_U127->din1(grp_fu_402_p1);
    myproject_mul_18seOg_x_U127->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U127->dout(grp_fu_402_p2);
    myproject_mul_18sfYi_x_U128 = new myproject_mul_18sfYi<1,3,18,9,27>("myproject_mul_18sfYi_x_U128");
    myproject_mul_18sfYi_x_U128->clk(ap_clk);
    myproject_mul_18sfYi_x_U128->reset(ap_rst);
    myproject_mul_18sfYi_x_U128->din0(data_1_V_read);
    myproject_mul_18sfYi_x_U128->din1(grp_fu_403_p1);
    myproject_mul_18sfYi_x_U128->ce(ap_var_for_const0);
    myproject_mul_18sfYi_x_U128->dout(grp_fu_403_p2);
    myproject_mul_18sg8j_x_U129 = new myproject_mul_18sg8j<1,3,18,9,26>("myproject_mul_18sg8j_x_U129");
    myproject_mul_18sg8j_x_U129->clk(ap_clk);
    myproject_mul_18sg8j_x_U129->reset(ap_rst);
    myproject_mul_18sg8j_x_U129->din0(grp_fu_404_p0);
    myproject_mul_18sg8j_x_U129->din1(grp_fu_404_p1);
    myproject_mul_18sg8j_x_U129->ce(ap_var_for_const0);
    myproject_mul_18sg8j_x_U129->dout(grp_fu_404_p2);
    myproject_mul_18sfYi_x_U130 = new myproject_mul_18sfYi<1,3,18,9,27>("myproject_mul_18sfYi_x_U130");
    myproject_mul_18sfYi_x_U130->clk(ap_clk);
    myproject_mul_18sfYi_x_U130->reset(ap_rst);
    myproject_mul_18sfYi_x_U130->din0(data_8_V_read);
    myproject_mul_18sfYi_x_U130->din1(grp_fu_405_p1);
    myproject_mul_18sfYi_x_U130->ce(ap_var_for_const0);
    myproject_mul_18sfYi_x_U130->dout(grp_fu_405_p2);
    myproject_mul_18seOg_x_U131 = new myproject_mul_18seOg<1,3,18,10,28>("myproject_mul_18seOg_x_U131");
    myproject_mul_18seOg_x_U131->clk(ap_clk);
    myproject_mul_18seOg_x_U131->reset(ap_rst);
    myproject_mul_18seOg_x_U131->din0(data_9_V_read);
    myproject_mul_18seOg_x_U131->din1(grp_fu_406_p1);
    myproject_mul_18seOg_x_U131->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U131->dout(grp_fu_406_p2);
    myproject_mul_18seOg_x_U132 = new myproject_mul_18seOg<1,3,18,10,28>("myproject_mul_18seOg_x_U132");
    myproject_mul_18seOg_x_U132->clk(ap_clk);
    myproject_mul_18seOg_x_U132->reset(ap_rst);
    myproject_mul_18seOg_x_U132->din0(grp_fu_407_p0);
    myproject_mul_18seOg_x_U132->din1(grp_fu_407_p1);
    myproject_mul_18seOg_x_U132->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U132->dout(grp_fu_407_p2);
    myproject_mul_18scud_x_U133 = new myproject_mul_18scud<1,3,18,10,27>("myproject_mul_18scud_x_U133");
    myproject_mul_18scud_x_U133->clk(ap_clk);
    myproject_mul_18scud_x_U133->reset(ap_rst);
    myproject_mul_18scud_x_U133->din0(grp_fu_408_p0);
    myproject_mul_18scud_x_U133->din1(grp_fu_408_p1);
    myproject_mul_18scud_x_U133->ce(ap_var_for_const0);
    myproject_mul_18scud_x_U133->dout(grp_fu_408_p2);
    myproject_mul_18seOg_x_U134 = new myproject_mul_18seOg<1,3,18,10,28>("myproject_mul_18seOg_x_U134");
    myproject_mul_18seOg_x_U134->clk(ap_clk);
    myproject_mul_18seOg_x_U134->reset(ap_rst);
    myproject_mul_18seOg_x_U134->din0(grp_fu_409_p0);
    myproject_mul_18seOg_x_U134->din1(grp_fu_409_p1);
    myproject_mul_18seOg_x_U134->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U134->dout(grp_fu_409_p2);
    myproject_mul_18seOg_x_U135 = new myproject_mul_18seOg<1,3,18,10,28>("myproject_mul_18seOg_x_U135");
    myproject_mul_18seOg_x_U135->clk(ap_clk);
    myproject_mul_18seOg_x_U135->reset(ap_rst);
    myproject_mul_18seOg_x_U135->din0(data_7_V_read);
    myproject_mul_18seOg_x_U135->din1(grp_fu_410_p1);
    myproject_mul_18seOg_x_U135->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U135->dout(grp_fu_410_p2);
    myproject_mul_18sfYi_x_U136 = new myproject_mul_18sfYi<1,3,18,9,27>("myproject_mul_18sfYi_x_U136");
    myproject_mul_18sfYi_x_U136->clk(ap_clk);
    myproject_mul_18sfYi_x_U136->reset(ap_rst);
    myproject_mul_18sfYi_x_U136->din0(data_14_V_read);
    myproject_mul_18sfYi_x_U136->din1(grp_fu_411_p1);
    myproject_mul_18sfYi_x_U136->ce(ap_var_for_const0);
    myproject_mul_18sfYi_x_U136->dout(grp_fu_411_p2);
    myproject_mul_18socq_U137 = new myproject_mul_18socq<1,3,18,6,24>("myproject_mul_18socq_U137");
    myproject_mul_18socq_U137->clk(ap_clk);
    myproject_mul_18socq_U137->reset(ap_rst);
    myproject_mul_18socq_U137->din0(grp_fu_412_p0);
    myproject_mul_18socq_U137->din1(grp_fu_412_p1);
    myproject_mul_18socq_U137->ce(ap_var_for_const0);
    myproject_mul_18socq_U137->dout(grp_fu_412_p2);
    myproject_mul_18sncg_x_U138 = new myproject_mul_18sncg<1,3,18,9,27>("myproject_mul_18sncg_x_U138");
    myproject_mul_18sncg_x_U138->clk(ap_clk);
    myproject_mul_18sncg_x_U138->reset(ap_rst);
    myproject_mul_18sncg_x_U138->din0(grp_fu_413_p0);
    myproject_mul_18sncg_x_U138->din1(grp_fu_413_p1);
    myproject_mul_18sncg_x_U138->ce(ap_var_for_const0);
    myproject_mul_18sncg_x_U138->dout(grp_fu_413_p2);
    myproject_mul_18seOg_x_U139 = new myproject_mul_18seOg<1,3,18,10,28>("myproject_mul_18seOg_x_U139");
    myproject_mul_18seOg_x_U139->clk(ap_clk);
    myproject_mul_18seOg_x_U139->reset(ap_rst);
    myproject_mul_18seOg_x_U139->din0(data_12_V_read);
    myproject_mul_18seOg_x_U139->din1(grp_fu_414_p1);
    myproject_mul_18seOg_x_U139->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U139->dout(grp_fu_414_p2);
    myproject_mul_18sg8j_x_U140 = new myproject_mul_18sg8j<1,3,18,9,26>("myproject_mul_18sg8j_x_U140");
    myproject_mul_18sg8j_x_U140->clk(ap_clk);
    myproject_mul_18sg8j_x_U140->reset(ap_rst);
    myproject_mul_18sg8j_x_U140->din0(grp_fu_415_p0);
    myproject_mul_18sg8j_x_U140->din1(grp_fu_415_p1);
    myproject_mul_18sg8j_x_U140->ce(ap_var_for_const0);
    myproject_mul_18sg8j_x_U140->dout(grp_fu_415_p2);
    myproject_mul_18sfYi_x_U141 = new myproject_mul_18sfYi<1,3,18,9,27>("myproject_mul_18sfYi_x_U141");
    myproject_mul_18sfYi_x_U141->clk(ap_clk);
    myproject_mul_18sfYi_x_U141->reset(ap_rst);
    myproject_mul_18sfYi_x_U141->din0(data_22_V_read);
    myproject_mul_18sfYi_x_U141->din1(grp_fu_416_p1);
    myproject_mul_18sfYi_x_U141->ce(ap_var_for_const0);
    myproject_mul_18sfYi_x_U141->dout(grp_fu_416_p2);
    myproject_mul_18sncg_x_U142 = new myproject_mul_18sncg<1,3,18,9,27>("myproject_mul_18sncg_x_U142");
    myproject_mul_18sncg_x_U142->clk(ap_clk);
    myproject_mul_18sncg_x_U142->reset(ap_rst);
    myproject_mul_18sncg_x_U142->din0(data_5_V_read);
    myproject_mul_18sncg_x_U142->din1(grp_fu_417_p1);
    myproject_mul_18sncg_x_U142->ce(ap_var_for_const0);
    myproject_mul_18sncg_x_U142->dout(grp_fu_417_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_10_cast_fu_1957_p1);
    sensitive << ( ap_port_reg_data_11_V_read );

    SC_METHOD(thread_OP1_V_12_cast_fu_1989_p1);
    sensitive << ( ap_port_reg_data_13_V_read );

    SC_METHOD(thread_OP1_V_14_cast_fu_1802_p1);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_OP1_V_16_cast_fu_1807_p1);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_OP1_V_17_cast_fu_1812_p1);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_OP1_V_19_cast_fu_1817_p1);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_OP1_V_20_cast_fu_1822_p1);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_OP1_V_23_cast_fu_2065_p1);
    sensitive << ( ap_port_reg_data_24_V_read );

    SC_METHOD(thread_OP1_V_24_cast_fu_2070_p1);
    sensitive << ( ap_port_reg_data_25_V_read );

    SC_METHOD(thread_OP1_V_25_cast_fu_2075_p1);
    sensitive << ( ap_port_reg_data_26_V_read );

    SC_METHOD(thread_OP1_V_26_cast_fu_2080_p1);
    sensitive << ( ap_port_reg_data_27_V_read );

    SC_METHOD(thread_OP1_V_28_cast_fu_2125_p1);
    sensitive << ( ap_port_reg_data_29_V_read );

    SC_METHOD(thread_OP1_V_29_cast_fu_2130_p1);
    sensitive << ( ap_port_reg_data_30_V_read );

    SC_METHOD(thread_OP1_V_30_cast_fu_2135_p1);
    sensitive << ( ap_port_reg_data_31_V_read );

    SC_METHOD(thread_OP1_V_3_cast_fu_1762_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_OP1_V_cast_fu_1787_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0_preg );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_pipeline_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( tmp30_fu_2562_p2 );
    sensitive << ( tmp15_fu_2554_p2 );

    SC_METHOD(thread_grp_fu_1715_p4);
    sensitive << ( grp_fu_412_p2 );

    SC_METHOD(thread_grp_fu_402_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_403_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_404_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_14_cast_fu_1802_p1 );
    sensitive << ( OP1_V_28_cast_fu_2125_p1 );

    SC_METHOD(thread_grp_fu_404_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_405_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_406_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_407_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_3_cast_fu_1762_p1 );
    sensitive << ( OP1_V_24_cast_fu_2070_p1 );

    SC_METHOD(thread_grp_fu_407_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_408_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_cast_fu_1787_p1 );
    sensitive << ( OP1_V_29_cast_fu_2130_p1 );

    SC_METHOD(thread_grp_fu_408_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_409_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_17_cast_fu_1812_p1 );
    sensitive << ( OP1_V_23_cast_fu_2065_p1 );

    SC_METHOD(thread_grp_fu_409_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_410_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_411_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_412_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_16_cast_fu_1807_p1 );
    sensitive << ( OP1_V_30_cast_fu_2135_p1 );

    SC_METHOD(thread_grp_fu_412_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_413_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_19_cast_fu_1817_p1 );
    sensitive << ( OP1_V_26_cast_fu_2080_p1 );

    SC_METHOD(thread_grp_fu_413_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_414_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_415_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_20_cast_fu_1822_p1 );
    sensitive << ( OP1_V_25_cast_fu_2075_p1 );

    SC_METHOD(thread_grp_fu_415_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_416_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_417_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_p_Val2_10_fu_1973_p2);
    sensitive << ( p_shl4_cast_fu_1969_p1 );
    sensitive << ( OP1_V_10_cast_fu_1957_p1 );

    SC_METHOD(thread_p_Val2_12_fu_2011_p2);
    sensitive << ( p_neg_fu_2005_p2 );
    sensitive << ( OP1_V_12_cast_fu_1989_p1 );

    SC_METHOD(thread_p_Val2_17_fu_2049_p2);
    sensitive << ( p_shl2_cast_fu_2045_p1 );

    SC_METHOD(thread_p_Val2_1_fu_2172_p2);
    sensitive << ( p_shl11_cast_fu_2168_p1 );
    sensitive << ( p_shl9_cast_fu_2157_p1 );

    SC_METHOD(thread_p_Val2_26_fu_2109_p2);
    sensitive << ( p_shl_cast_fu_2093_p1 );
    sensitive << ( p_shl1_cast_fu_2105_p1 );

    SC_METHOD(thread_p_Val2_4_fu_1901_p2);
    sensitive << ( p_shl7_cast_fu_1885_p1 );
    sensitive << ( p_shl8_cast_fu_1897_p1 );

    SC_METHOD(thread_p_Val2_6_fu_1941_p2);
    sensitive << ( p_shl5_cast_fu_1925_p1 );
    sensitive << ( p_shl6_cast_fu_1937_p1 );

    SC_METHOD(thread_p_Val2_s_fu_1861_p2);
    sensitive << ( p_shl14_cast_fu_1857_p1 );
    sensitive << ( p_shl12_cast_fu_1845_p1 );

    SC_METHOD(thread_p_neg_fu_2005_p2);
    sensitive << ( p_shl3_cast_fu_2001_p1 );

    SC_METHOD(thread_p_shl10_fu_1837_p3);
    sensitive << ( ap_port_reg_data_0_V_read );

    SC_METHOD(thread_p_shl11_cast_fu_2168_p1);
    sensitive << ( p_shl11_fu_2161_p3 );

    SC_METHOD(thread_p_shl11_fu_2161_p3);
    sensitive << ( data_2_V_read_2_reg_2653 );

    SC_METHOD(thread_p_shl12_cast_fu_1845_p1);
    sensitive << ( p_shl10_fu_1837_p3 );

    SC_METHOD(thread_p_shl12_fu_1849_p3);
    sensitive << ( ap_port_reg_data_0_V_read );

    SC_METHOD(thread_p_shl14_cast_fu_1857_p1);
    sensitive << ( p_shl12_fu_1849_p3 );

    SC_METHOD(thread_p_shl1_cast_fu_2105_p1);
    sensitive << ( p_shl1_fu_2097_p3 );

    SC_METHOD(thread_p_shl1_fu_2097_p3);
    sensitive << ( ap_port_reg_data_28_V_read );

    SC_METHOD(thread_p_shl2_cast_fu_2045_p1);
    sensitive << ( p_shl2_fu_2037_p3 );

    SC_METHOD(thread_p_shl2_fu_2037_p3);
    sensitive << ( ap_port_reg_data_19_V_read );

    SC_METHOD(thread_p_shl3_cast_fu_2001_p1);
    sensitive << ( p_shl3_fu_1993_p3 );

    SC_METHOD(thread_p_shl3_fu_1993_p3);
    sensitive << ( ap_port_reg_data_13_V_read );

    SC_METHOD(thread_p_shl4_cast_fu_1969_p1);
    sensitive << ( p_shl4_fu_1961_p3 );

    SC_METHOD(thread_p_shl4_fu_1961_p3);
    sensitive << ( ap_port_reg_data_11_V_read );

    SC_METHOD(thread_p_shl5_cast_fu_1925_p1);
    sensitive << ( p_shl5_fu_1917_p3 );

    SC_METHOD(thread_p_shl5_fu_1917_p3);
    sensitive << ( ap_port_reg_data_6_V_read );

    SC_METHOD(thread_p_shl6_cast_fu_1937_p1);
    sensitive << ( p_shl6_fu_1929_p3 );

    SC_METHOD(thread_p_shl6_fu_1929_p3);
    sensitive << ( ap_port_reg_data_6_V_read );

    SC_METHOD(thread_p_shl7_cast_fu_1885_p1);
    sensitive << ( p_shl7_fu_1877_p3 );

    SC_METHOD(thread_p_shl7_fu_1877_p3);
    sensitive << ( ap_port_reg_data_4_V_read );

    SC_METHOD(thread_p_shl8_cast_fu_1897_p1);
    sensitive << ( p_shl8_fu_1889_p3 );

    SC_METHOD(thread_p_shl8_fu_1889_p3);
    sensitive << ( ap_port_reg_data_4_V_read );

    SC_METHOD(thread_p_shl9_cast_fu_2157_p1);
    sensitive << ( p_shl9_fu_2150_p3 );

    SC_METHOD(thread_p_shl9_fu_2150_p3);
    sensitive << ( data_2_V_read_2_reg_2653 );

    SC_METHOD(thread_p_shl_cast_fu_2093_p1);
    sensitive << ( p_shl_fu_2085_p3 );

    SC_METHOD(thread_p_shl_fu_2085_p3);
    sensitive << ( ap_port_reg_data_28_V_read );

    SC_METHOD(thread_tmp10_fu_2420_p2);
    sensitive << ( tmp9_fu_2414_p2 );
    sensitive << ( tmp8_fu_2409_p2 );

    SC_METHOD(thread_tmp11_fu_2426_p2);
    sensitive << ( tmp_3_s_reg_2769 );
    sensitive << ( tmp_19_fu_2329_p1 );

    SC_METHOD(thread_tmp12_fu_2431_p2);
    sensitive << ( tmp_21_fu_2332_p1 );
    sensitive << ( tmp_23_fu_2335_p1 );

    SC_METHOD(thread_tmp13_fu_2437_p2);
    sensitive << ( tmp12_fu_2431_p2 );
    sensitive << ( tmp11_fu_2426_p2 );

    SC_METHOD(thread_tmp14_fu_2443_p2);
    sensitive << ( tmp13_fu_2437_p2 );
    sensitive << ( tmp10_fu_2420_p2 );

    SC_METHOD(thread_tmp15_fu_2554_p2);
    sensitive << ( tmp7_reg_2819 );
    sensitive << ( tmp14_reg_2824 );

    SC_METHOD(thread_tmp16_fu_2449_p2);
    sensitive << ( reg_1753 );
    sensitive << ( tmp_26_fu_2342_p1 );

    SC_METHOD(thread_tmp17_cast_fu_2455_p1);
    sensitive << ( tmp17_reg_2799 );

    SC_METHOD(thread_tmp17_fu_2295_p2);
    sensitive << ( tmp_28_cast_fu_2258_p1 );
    sensitive << ( tmp_30_cast_fu_2271_p1 );

    SC_METHOD(thread_tmp18_fu_2458_p2);
    sensitive << ( tmp17_cast_fu_2455_p1 );
    sensitive << ( tmp16_fu_2449_p2 );

    SC_METHOD(thread_tmp19_fu_2499_p2);
    sensitive << ( tmp_28_fu_2476_p1 );
    sensitive << ( tmp_30_fu_2479_p1 );

    SC_METHOD(thread_tmp1_fu_2369_p2);
    sensitive << ( tmp_6_fu_2301_p1 );
    sensitive << ( tmp_9_fu_2304_p1 );

    SC_METHOD(thread_tmp20_fu_2505_p2);
    sensitive << ( reg_1753 );
    sensitive << ( tmp_3_3_reg_2794 );

    SC_METHOD(thread_tmp21_fu_2510_p2);
    sensitive << ( tmp20_fu_2505_p2 );
    sensitive << ( tmp19_fu_2499_p2 );

    SC_METHOD(thread_tmp22_fu_2558_p2);
    sensitive << ( tmp18_reg_2829 );
    sensitive << ( tmp21_reg_2839 );

    SC_METHOD(thread_tmp23_fu_2516_p2);
    sensitive << ( tmp_3_5_reg_2804 );
    sensitive << ( tmp_32_fu_2482_p1 );

    SC_METHOD(thread_tmp24_fu_2521_p2);
    sensitive << ( tmp_34_fu_2485_p1 );
    sensitive << ( tmp_36_fu_2488_p1 );

    SC_METHOD(thread_tmp25_fu_2527_p2);
    sensitive << ( tmp24_fu_2521_p2 );
    sensitive << ( tmp23_fu_2516_p2 );

    SC_METHOD(thread_tmp26_fu_2533_p2);
    sensitive << ( tmp_38_fu_2491_p1 );
    sensitive << ( tmp_40_fu_2495_p1 );

    SC_METHOD(thread_tmp27_fu_2464_p2);
    sensitive << ( tmp_3_15_cast_fu_2339_p1 );

    SC_METHOD(thread_tmp28_cast_fu_2539_p1);
    sensitive << ( tmp28_reg_2834 );

    SC_METHOD(thread_tmp28_fu_2470_p2);
    sensitive << ( tmp27_fu_2464_p2 );
    sensitive << ( tmp_46_cast_fu_2365_p1 );

    SC_METHOD(thread_tmp29_fu_2542_p2);
    sensitive << ( tmp28_cast_fu_2539_p1 );
    sensitive << ( tmp26_fu_2533_p2 );

    SC_METHOD(thread_tmp2_fu_2375_p2);
    sensitive << ( tmp_3_2_reg_2739 );
    sensitive << ( tmp_1_fu_2307_p1 );

    SC_METHOD(thread_tmp30_fu_2562_p2);
    sensitive << ( tmp31_reg_2844 );
    sensitive << ( tmp22_fu_2558_p2 );

    SC_METHOD(thread_tmp31_fu_2548_p2);
    sensitive << ( tmp29_fu_2542_p2 );
    sensitive << ( tmp25_fu_2527_p2 );

    SC_METHOD(thread_tmp3_fu_2380_p2);
    sensitive << ( tmp2_fu_2375_p2 );
    sensitive << ( tmp1_fu_2369_p2 );

    SC_METHOD(thread_tmp4_fu_2386_p2);
    sensitive << ( tmp_3_fu_2310_p1 );
    sensitive << ( tmp_7_fu_2313_p1 );

    SC_METHOD(thread_tmp5_fu_2392_p2);
    sensitive << ( tmp_3_7_reg_2754 );
    sensitive << ( tmp_11_fu_2316_p1 );

    SC_METHOD(thread_tmp6_fu_2397_p2);
    sensitive << ( tmp5_fu_2392_p2 );
    sensitive << ( tmp4_fu_2386_p2 );

    SC_METHOD(thread_tmp7_fu_2403_p2);
    sensitive << ( tmp6_fu_2397_p2 );
    sensitive << ( tmp3_fu_2380_p2 );

    SC_METHOD(thread_tmp8_fu_2409_p2);
    sensitive << ( tmp_3_9_reg_2764 );
    sensitive << ( tmp_13_fu_2319_p1 );

    SC_METHOD(thread_tmp9_fu_2414_p2);
    sensitive << ( tmp_15_fu_2322_p1 );
    sensitive << ( tmp_17_fu_2326_p1 );

    SC_METHOD(thread_tmp_11_fu_2316_p1);
    sensitive << ( tmp_10_reg_2669 );

    SC_METHOD(thread_tmp_13_fu_2319_p1);
    sensitive << ( tmp_12_reg_2759 );

    SC_METHOD(thread_tmp_15_fu_2322_p1);
    sensitive << ( reg_1745 );

    SC_METHOD(thread_tmp_17_fu_2326_p1);
    sensitive << ( tmp_16_reg_2674 );

    SC_METHOD(thread_tmp_19_fu_2329_p1);
    sensitive << ( tmp_18_reg_2679 );

    SC_METHOD(thread_tmp_1_fu_2307_p1);
    sensitive << ( tmp_s_reg_2744 );

    SC_METHOD(thread_tmp_21_fu_2332_p1);
    sensitive << ( tmp_20_reg_2774 );

    SC_METHOD(thread_tmp_23_fu_2335_p1);
    sensitive << ( reg_1749 );

    SC_METHOD(thread_tmp_26_fu_2342_p1);
    sensitive << ( tmp_25_reg_2779 );

    SC_METHOD(thread_tmp_28_cast_fu_2258_p1);
    sensitive << ( tmp_45_reg_2689 );

    SC_METHOD(thread_tmp_28_fu_2476_p1);
    sensitive << ( tmp_27_reg_2784 );

    SC_METHOD(thread_tmp_30_cast_fu_2271_p1);
    sensitive << ( tmp_46_fu_2261_p4 );

    SC_METHOD(thread_tmp_30_fu_2479_p1);
    sensitive << ( tmp_29_reg_2789 );

    SC_METHOD(thread_tmp_32_fu_2482_p1);
    sensitive << ( tmp_31_reg_2809 );

    SC_METHOD(thread_tmp_34_fu_2485_p1);
    sensitive << ( tmp_33_reg_2814 );

    SC_METHOD(thread_tmp_36_fu_2488_p1);
    sensitive << ( ap_pipeline_reg_pp0_iter1_tmp_35_reg_2714 );

    SC_METHOD(thread_tmp_38_fu_2491_p1);
    sensitive << ( reg_1749 );

    SC_METHOD(thread_tmp_3_15_cast_fu_2339_p1);
    sensitive << ( tmp_24_reg_2684 );

    SC_METHOD(thread_tmp_3_fu_2310_p1);
    sensitive << ( tmp_2_reg_2664 );

    SC_METHOD(thread_tmp_40_fu_2495_p1);
    sensitive << ( reg_1745 );

    SC_METHOD(thread_tmp_46_cast_fu_2365_p1);
    sensitive << ( grp_fu_1715_p4 );

    SC_METHOD(thread_tmp_46_fu_2261_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_fu_413_p2 );

    SC_METHOD(thread_tmp_46_fu_2261_p4);
    sensitive << ( tmp_46_fu_2261_p1 );

    SC_METHOD(thread_tmp_6_fu_2301_p1);
    sensitive << ( tmp_5_reg_2659 );

    SC_METHOD(thread_tmp_7_fu_2313_p1);
    sensitive << ( tmp_4_reg_2749 );

    SC_METHOD(thread_tmp_9_fu_2304_p1);
    sensitive << ( tmp_8_reg_2734 );

    SC_METHOD(thread_tmp_s_fu_2188_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_fu_407_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_pipeline_idle_pp0 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "01";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0_preg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "compute_layer_0_0_0_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, data_20_V_read, "(port)data_20_V_read");
    sc_trace(mVcdFile, data_21_V_read, "(port)data_21_V_read");
    sc_trace(mVcdFile, data_22_V_read, "(port)data_22_V_read");
    sc_trace(mVcdFile, data_23_V_read, "(port)data_23_V_read");
    sc_trace(mVcdFile, data_24_V_read, "(port)data_24_V_read");
    sc_trace(mVcdFile, data_25_V_read, "(port)data_25_V_read");
    sc_trace(mVcdFile, data_26_V_read, "(port)data_26_V_read");
    sc_trace(mVcdFile, data_27_V_read, "(port)data_27_V_read");
    sc_trace(mVcdFile, data_28_V_read, "(port)data_28_V_read");
    sc_trace(mVcdFile, data_29_V_read, "(port)data_29_V_read");
    sc_trace(mVcdFile, data_30_V_read, "(port)data_30_V_read");
    sc_trace(mVcdFile, data_31_V_read, "(port)data_31_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, reg_1745, "reg_1745");
    sc_trace(mVcdFile, reg_1749, "reg_1749");
    sc_trace(mVcdFile, reg_1753, "reg_1753");
    sc_trace(mVcdFile, OP1_V_3_cast_fu_1762_p1, "OP1_V_3_cast_fu_1762_p1");
    sc_trace(mVcdFile, OP1_V_cast_fu_1787_p1, "OP1_V_cast_fu_1787_p1");
    sc_trace(mVcdFile, OP1_V_14_cast_fu_1802_p1, "OP1_V_14_cast_fu_1802_p1");
    sc_trace(mVcdFile, OP1_V_16_cast_fu_1807_p1, "OP1_V_16_cast_fu_1807_p1");
    sc_trace(mVcdFile, OP1_V_17_cast_fu_1812_p1, "OP1_V_17_cast_fu_1812_p1");
    sc_trace(mVcdFile, OP1_V_19_cast_fu_1817_p1, "OP1_V_19_cast_fu_1817_p1");
    sc_trace(mVcdFile, OP1_V_20_cast_fu_1822_p1, "OP1_V_20_cast_fu_1822_p1");
    sc_trace(mVcdFile, data_2_V_read_2_reg_2653, "data_2_V_read_2_reg_2653");
    sc_trace(mVcdFile, tmp_5_reg_2659, "tmp_5_reg_2659");
    sc_trace(mVcdFile, tmp_2_reg_2664, "tmp_2_reg_2664");
    sc_trace(mVcdFile, tmp_10_reg_2669, "tmp_10_reg_2669");
    sc_trace(mVcdFile, tmp_16_reg_2674, "tmp_16_reg_2674");
    sc_trace(mVcdFile, tmp_18_reg_2679, "tmp_18_reg_2679");
    sc_trace(mVcdFile, tmp_24_reg_2684, "tmp_24_reg_2684");
    sc_trace(mVcdFile, tmp_45_reg_2689, "tmp_45_reg_2689");
    sc_trace(mVcdFile, OP1_V_23_cast_fu_2065_p1, "OP1_V_23_cast_fu_2065_p1");
    sc_trace(mVcdFile, OP1_V_24_cast_fu_2070_p1, "OP1_V_24_cast_fu_2070_p1");
    sc_trace(mVcdFile, OP1_V_25_cast_fu_2075_p1, "OP1_V_25_cast_fu_2075_p1");
    sc_trace(mVcdFile, OP1_V_26_cast_fu_2080_p1, "OP1_V_26_cast_fu_2080_p1");
    sc_trace(mVcdFile, tmp_35_reg_2714, "tmp_35_reg_2714");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_tmp_35_reg_2714, "ap_pipeline_reg_pp0_iter1_tmp_35_reg_2714");
    sc_trace(mVcdFile, OP1_V_28_cast_fu_2125_p1, "OP1_V_28_cast_fu_2125_p1");
    sc_trace(mVcdFile, OP1_V_29_cast_fu_2130_p1, "OP1_V_29_cast_fu_2130_p1");
    sc_trace(mVcdFile, OP1_V_30_cast_fu_2135_p1, "OP1_V_30_cast_fu_2135_p1");
    sc_trace(mVcdFile, tmp_8_reg_2734, "tmp_8_reg_2734");
    sc_trace(mVcdFile, tmp_3_2_reg_2739, "tmp_3_2_reg_2739");
    sc_trace(mVcdFile, tmp_s_reg_2744, "tmp_s_reg_2744");
    sc_trace(mVcdFile, tmp_4_reg_2749, "tmp_4_reg_2749");
    sc_trace(mVcdFile, tmp_3_7_reg_2754, "tmp_3_7_reg_2754");
    sc_trace(mVcdFile, tmp_12_reg_2759, "tmp_12_reg_2759");
    sc_trace(mVcdFile, tmp_3_9_reg_2764, "tmp_3_9_reg_2764");
    sc_trace(mVcdFile, tmp_3_s_reg_2769, "tmp_3_s_reg_2769");
    sc_trace(mVcdFile, tmp_20_reg_2774, "tmp_20_reg_2774");
    sc_trace(mVcdFile, grp_fu_1715_p4, "grp_fu_1715_p4");
    sc_trace(mVcdFile, tmp_25_reg_2779, "tmp_25_reg_2779");
    sc_trace(mVcdFile, tmp_27_reg_2784, "tmp_27_reg_2784");
    sc_trace(mVcdFile, tmp_29_reg_2789, "tmp_29_reg_2789");
    sc_trace(mVcdFile, tmp_3_3_reg_2794, "tmp_3_3_reg_2794");
    sc_trace(mVcdFile, tmp17_fu_2295_p2, "tmp17_fu_2295_p2");
    sc_trace(mVcdFile, tmp17_reg_2799, "tmp17_reg_2799");
    sc_trace(mVcdFile, tmp_3_5_reg_2804, "tmp_3_5_reg_2804");
    sc_trace(mVcdFile, tmp_31_reg_2809, "tmp_31_reg_2809");
    sc_trace(mVcdFile, tmp_33_reg_2814, "tmp_33_reg_2814");
    sc_trace(mVcdFile, tmp7_fu_2403_p2, "tmp7_fu_2403_p2");
    sc_trace(mVcdFile, tmp7_reg_2819, "tmp7_reg_2819");
    sc_trace(mVcdFile, tmp14_fu_2443_p2, "tmp14_fu_2443_p2");
    sc_trace(mVcdFile, tmp14_reg_2824, "tmp14_reg_2824");
    sc_trace(mVcdFile, tmp18_fu_2458_p2, "tmp18_fu_2458_p2");
    sc_trace(mVcdFile, tmp18_reg_2829, "tmp18_reg_2829");
    sc_trace(mVcdFile, tmp28_fu_2470_p2, "tmp28_fu_2470_p2");
    sc_trace(mVcdFile, tmp28_reg_2834, "tmp28_reg_2834");
    sc_trace(mVcdFile, tmp21_fu_2510_p2, "tmp21_fu_2510_p2");
    sc_trace(mVcdFile, tmp21_reg_2839, "tmp21_reg_2839");
    sc_trace(mVcdFile, tmp31_fu_2548_p2, "tmp31_fu_2548_p2");
    sc_trace(mVcdFile, tmp31_reg_2844, "tmp31_reg_2844");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0_preg, "ap_enable_reg_pp0_iter0_preg");
    sc_trace(mVcdFile, ap_port_reg_data_0_V_read, "ap_port_reg_data_0_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_2_V_read, "ap_port_reg_data_2_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_4_V_read, "ap_port_reg_data_4_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_6_V_read, "ap_port_reg_data_6_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_11_V_read, "ap_port_reg_data_11_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_13_V_read, "ap_port_reg_data_13_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_16_V_read, "ap_port_reg_data_16_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_19_V_read, "ap_port_reg_data_19_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_24_V_read, "ap_port_reg_data_24_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_25_V_read, "ap_port_reg_data_25_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_26_V_read, "ap_port_reg_data_26_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_27_V_read, "ap_port_reg_data_27_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_28_V_read, "ap_port_reg_data_28_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_29_V_read, "ap_port_reg_data_29_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_30_V_read, "ap_port_reg_data_30_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_31_V_read, "ap_port_reg_data_31_V_read");
    sc_trace(mVcdFile, grp_fu_402_p1, "grp_fu_402_p1");
    sc_trace(mVcdFile, grp_fu_403_p1, "grp_fu_403_p1");
    sc_trace(mVcdFile, grp_fu_404_p0, "grp_fu_404_p0");
    sc_trace(mVcdFile, grp_fu_404_p1, "grp_fu_404_p1");
    sc_trace(mVcdFile, grp_fu_405_p1, "grp_fu_405_p1");
    sc_trace(mVcdFile, grp_fu_406_p1, "grp_fu_406_p1");
    sc_trace(mVcdFile, grp_fu_407_p0, "grp_fu_407_p0");
    sc_trace(mVcdFile, grp_fu_407_p1, "grp_fu_407_p1");
    sc_trace(mVcdFile, grp_fu_408_p0, "grp_fu_408_p0");
    sc_trace(mVcdFile, grp_fu_408_p1, "grp_fu_408_p1");
    sc_trace(mVcdFile, grp_fu_409_p0, "grp_fu_409_p0");
    sc_trace(mVcdFile, grp_fu_409_p1, "grp_fu_409_p1");
    sc_trace(mVcdFile, grp_fu_410_p1, "grp_fu_410_p1");
    sc_trace(mVcdFile, grp_fu_411_p1, "grp_fu_411_p1");
    sc_trace(mVcdFile, grp_fu_412_p0, "grp_fu_412_p0");
    sc_trace(mVcdFile, grp_fu_412_p1, "grp_fu_412_p1");
    sc_trace(mVcdFile, grp_fu_413_p0, "grp_fu_413_p0");
    sc_trace(mVcdFile, grp_fu_413_p1, "grp_fu_413_p1");
    sc_trace(mVcdFile, grp_fu_414_p1, "grp_fu_414_p1");
    sc_trace(mVcdFile, grp_fu_415_p0, "grp_fu_415_p0");
    sc_trace(mVcdFile, grp_fu_415_p1, "grp_fu_415_p1");
    sc_trace(mVcdFile, grp_fu_416_p1, "grp_fu_416_p1");
    sc_trace(mVcdFile, grp_fu_417_p1, "grp_fu_417_p1");
    sc_trace(mVcdFile, grp_fu_408_p2, "grp_fu_408_p2");
    sc_trace(mVcdFile, grp_fu_404_p2, "grp_fu_404_p2");
    sc_trace(mVcdFile, grp_fu_412_p2, "grp_fu_412_p2");
    sc_trace(mVcdFile, grp_fu_409_p2, "grp_fu_409_p2");
    sc_trace(mVcdFile, grp_fu_415_p2, "grp_fu_415_p2");
    sc_trace(mVcdFile, p_shl10_fu_1837_p3, "p_shl10_fu_1837_p3");
    sc_trace(mVcdFile, p_shl12_fu_1849_p3, "p_shl12_fu_1849_p3");
    sc_trace(mVcdFile, p_shl14_cast_fu_1857_p1, "p_shl14_cast_fu_1857_p1");
    sc_trace(mVcdFile, p_shl12_cast_fu_1845_p1, "p_shl12_cast_fu_1845_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_1861_p2, "p_Val2_s_fu_1861_p2");
    sc_trace(mVcdFile, p_shl7_fu_1877_p3, "p_shl7_fu_1877_p3");
    sc_trace(mVcdFile, p_shl8_fu_1889_p3, "p_shl8_fu_1889_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_1885_p1, "p_shl7_cast_fu_1885_p1");
    sc_trace(mVcdFile, p_shl8_cast_fu_1897_p1, "p_shl8_cast_fu_1897_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_1901_p2, "p_Val2_4_fu_1901_p2");
    sc_trace(mVcdFile, p_shl5_fu_1917_p3, "p_shl5_fu_1917_p3");
    sc_trace(mVcdFile, p_shl6_fu_1929_p3, "p_shl6_fu_1929_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_1925_p1, "p_shl5_cast_fu_1925_p1");
    sc_trace(mVcdFile, p_shl6_cast_fu_1937_p1, "p_shl6_cast_fu_1937_p1");
    sc_trace(mVcdFile, p_Val2_6_fu_1941_p2, "p_Val2_6_fu_1941_p2");
    sc_trace(mVcdFile, p_shl4_fu_1961_p3, "p_shl4_fu_1961_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_1969_p1, "p_shl4_cast_fu_1969_p1");
    sc_trace(mVcdFile, OP1_V_10_cast_fu_1957_p1, "OP1_V_10_cast_fu_1957_p1");
    sc_trace(mVcdFile, p_Val2_10_fu_1973_p2, "p_Val2_10_fu_1973_p2");
    sc_trace(mVcdFile, p_shl3_fu_1993_p3, "p_shl3_fu_1993_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_2001_p1, "p_shl3_cast_fu_2001_p1");
    sc_trace(mVcdFile, p_neg_fu_2005_p2, "p_neg_fu_2005_p2");
    sc_trace(mVcdFile, OP1_V_12_cast_fu_1989_p1, "OP1_V_12_cast_fu_1989_p1");
    sc_trace(mVcdFile, p_Val2_12_fu_2011_p2, "p_Val2_12_fu_2011_p2");
    sc_trace(mVcdFile, p_shl2_fu_2037_p3, "p_shl2_fu_2037_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_2045_p1, "p_shl2_cast_fu_2045_p1");
    sc_trace(mVcdFile, p_Val2_17_fu_2049_p2, "p_Val2_17_fu_2049_p2");
    sc_trace(mVcdFile, p_shl_fu_2085_p3, "p_shl_fu_2085_p3");
    sc_trace(mVcdFile, p_shl1_fu_2097_p3, "p_shl1_fu_2097_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_2093_p1, "p_shl_cast_fu_2093_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_2105_p1, "p_shl1_cast_fu_2105_p1");
    sc_trace(mVcdFile, p_Val2_26_fu_2109_p2, "p_Val2_26_fu_2109_p2");
    sc_trace(mVcdFile, grp_fu_403_p2, "grp_fu_403_p2");
    sc_trace(mVcdFile, p_shl9_fu_2150_p3, "p_shl9_fu_2150_p3");
    sc_trace(mVcdFile, p_shl11_fu_2161_p3, "p_shl11_fu_2161_p3");
    sc_trace(mVcdFile, p_shl11_cast_fu_2168_p1, "p_shl11_cast_fu_2168_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_2157_p1, "p_shl9_cast_fu_2157_p1");
    sc_trace(mVcdFile, p_Val2_1_fu_2172_p2, "p_Val2_1_fu_2172_p2");
    sc_trace(mVcdFile, tmp_s_fu_2188_p1, "tmp_s_fu_2188_p1");
    sc_trace(mVcdFile, grp_fu_407_p2, "grp_fu_407_p2");
    sc_trace(mVcdFile, grp_fu_417_p2, "grp_fu_417_p2");
    sc_trace(mVcdFile, grp_fu_410_p2, "grp_fu_410_p2");
    sc_trace(mVcdFile, grp_fu_405_p2, "grp_fu_405_p2");
    sc_trace(mVcdFile, grp_fu_406_p2, "grp_fu_406_p2");
    sc_trace(mVcdFile, grp_fu_414_p2, "grp_fu_414_p2");
    sc_trace(mVcdFile, grp_fu_411_p2, "grp_fu_411_p2");
    sc_trace(mVcdFile, tmp_46_fu_2261_p1, "tmp_46_fu_2261_p1");
    sc_trace(mVcdFile, grp_fu_413_p2, "grp_fu_413_p2");
    sc_trace(mVcdFile, tmp_46_fu_2261_p4, "tmp_46_fu_2261_p4");
    sc_trace(mVcdFile, grp_fu_416_p2, "grp_fu_416_p2");
    sc_trace(mVcdFile, grp_fu_402_p2, "grp_fu_402_p2");
    sc_trace(mVcdFile, tmp_28_cast_fu_2258_p1, "tmp_28_cast_fu_2258_p1");
    sc_trace(mVcdFile, tmp_30_cast_fu_2271_p1, "tmp_30_cast_fu_2271_p1");
    sc_trace(mVcdFile, tmp_6_fu_2301_p1, "tmp_6_fu_2301_p1");
    sc_trace(mVcdFile, tmp_9_fu_2304_p1, "tmp_9_fu_2304_p1");
    sc_trace(mVcdFile, tmp_1_fu_2307_p1, "tmp_1_fu_2307_p1");
    sc_trace(mVcdFile, tmp2_fu_2375_p2, "tmp2_fu_2375_p2");
    sc_trace(mVcdFile, tmp1_fu_2369_p2, "tmp1_fu_2369_p2");
    sc_trace(mVcdFile, tmp_3_fu_2310_p1, "tmp_3_fu_2310_p1");
    sc_trace(mVcdFile, tmp_7_fu_2313_p1, "tmp_7_fu_2313_p1");
    sc_trace(mVcdFile, tmp_11_fu_2316_p1, "tmp_11_fu_2316_p1");
    sc_trace(mVcdFile, tmp5_fu_2392_p2, "tmp5_fu_2392_p2");
    sc_trace(mVcdFile, tmp4_fu_2386_p2, "tmp4_fu_2386_p2");
    sc_trace(mVcdFile, tmp6_fu_2397_p2, "tmp6_fu_2397_p2");
    sc_trace(mVcdFile, tmp3_fu_2380_p2, "tmp3_fu_2380_p2");
    sc_trace(mVcdFile, tmp_13_fu_2319_p1, "tmp_13_fu_2319_p1");
    sc_trace(mVcdFile, tmp_15_fu_2322_p1, "tmp_15_fu_2322_p1");
    sc_trace(mVcdFile, tmp_17_fu_2326_p1, "tmp_17_fu_2326_p1");
    sc_trace(mVcdFile, tmp9_fu_2414_p2, "tmp9_fu_2414_p2");
    sc_trace(mVcdFile, tmp8_fu_2409_p2, "tmp8_fu_2409_p2");
    sc_trace(mVcdFile, tmp_19_fu_2329_p1, "tmp_19_fu_2329_p1");
    sc_trace(mVcdFile, tmp_21_fu_2332_p1, "tmp_21_fu_2332_p1");
    sc_trace(mVcdFile, tmp_23_fu_2335_p1, "tmp_23_fu_2335_p1");
    sc_trace(mVcdFile, tmp12_fu_2431_p2, "tmp12_fu_2431_p2");
    sc_trace(mVcdFile, tmp11_fu_2426_p2, "tmp11_fu_2426_p2");
    sc_trace(mVcdFile, tmp13_fu_2437_p2, "tmp13_fu_2437_p2");
    sc_trace(mVcdFile, tmp10_fu_2420_p2, "tmp10_fu_2420_p2");
    sc_trace(mVcdFile, tmp_26_fu_2342_p1, "tmp_26_fu_2342_p1");
    sc_trace(mVcdFile, tmp17_cast_fu_2455_p1, "tmp17_cast_fu_2455_p1");
    sc_trace(mVcdFile, tmp16_fu_2449_p2, "tmp16_fu_2449_p2");
    sc_trace(mVcdFile, tmp_3_15_cast_fu_2339_p1, "tmp_3_15_cast_fu_2339_p1");
    sc_trace(mVcdFile, tmp27_fu_2464_p2, "tmp27_fu_2464_p2");
    sc_trace(mVcdFile, tmp_46_cast_fu_2365_p1, "tmp_46_cast_fu_2365_p1");
    sc_trace(mVcdFile, tmp_28_fu_2476_p1, "tmp_28_fu_2476_p1");
    sc_trace(mVcdFile, tmp_30_fu_2479_p1, "tmp_30_fu_2479_p1");
    sc_trace(mVcdFile, tmp20_fu_2505_p2, "tmp20_fu_2505_p2");
    sc_trace(mVcdFile, tmp19_fu_2499_p2, "tmp19_fu_2499_p2");
    sc_trace(mVcdFile, tmp_32_fu_2482_p1, "tmp_32_fu_2482_p1");
    sc_trace(mVcdFile, tmp_34_fu_2485_p1, "tmp_34_fu_2485_p1");
    sc_trace(mVcdFile, tmp_36_fu_2488_p1, "tmp_36_fu_2488_p1");
    sc_trace(mVcdFile, tmp24_fu_2521_p2, "tmp24_fu_2521_p2");
    sc_trace(mVcdFile, tmp23_fu_2516_p2, "tmp23_fu_2516_p2");
    sc_trace(mVcdFile, tmp_38_fu_2491_p1, "tmp_38_fu_2491_p1");
    sc_trace(mVcdFile, tmp_40_fu_2495_p1, "tmp_40_fu_2495_p1");
    sc_trace(mVcdFile, tmp28_cast_fu_2539_p1, "tmp28_cast_fu_2539_p1");
    sc_trace(mVcdFile, tmp26_fu_2533_p2, "tmp26_fu_2533_p2");
    sc_trace(mVcdFile, tmp29_fu_2542_p2, "tmp29_fu_2542_p2");
    sc_trace(mVcdFile, tmp25_fu_2527_p2, "tmp25_fu_2527_p2");
    sc_trace(mVcdFile, tmp22_fu_2558_p2, "tmp22_fu_2558_p2");
    sc_trace(mVcdFile, tmp30_fu_2562_p2, "tmp30_fu_2562_p2");
    sc_trace(mVcdFile, tmp15_fu_2554_p2, "tmp15_fu_2554_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_pipeline_idle_pp0, "ap_pipeline_idle_pp0");
#endif

    }
}

compute_layer_0_0_0_1::~compute_layer_0_0_0_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_mul_18seOg_x_U127;
    delete myproject_mul_18sfYi_x_U128;
    delete myproject_mul_18sg8j_x_U129;
    delete myproject_mul_18sfYi_x_U130;
    delete myproject_mul_18seOg_x_U131;
    delete myproject_mul_18seOg_x_U132;
    delete myproject_mul_18scud_x_U133;
    delete myproject_mul_18seOg_x_U134;
    delete myproject_mul_18seOg_x_U135;
    delete myproject_mul_18sfYi_x_U136;
    delete myproject_mul_18socq_U137;
    delete myproject_mul_18sncg_x_U138;
    delete myproject_mul_18seOg_x_U139;
    delete myproject_mul_18sg8j_x_U140;
    delete myproject_mul_18sfYi_x_U141;
    delete myproject_mul_18sncg_x_U142;
}

void compute_layer_0_0_0_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void compute_layer_0_0_0_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0_preg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_enable_reg_pp0_iter0_preg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()))) {
        ap_pipeline_reg_pp0_iter1_tmp_35_reg_2714 = tmp_35_reg_2714.read();
        data_2_V_read_2_reg_2653 = ap_port_reg_data_2_V_read.read();
        tmp14_reg_2824 = tmp14_fu_2443_p2.read();
        tmp18_reg_2829 = tmp18_fu_2458_p2.read();
        tmp28_reg_2834 = tmp28_fu_2470_p2.read();
        tmp7_reg_2819 = tmp7_fu_2403_p2.read();
        tmp_10_reg_2669 = p_Val2_6_fu_1941_p2.read().range(25, 10);
        tmp_16_reg_2674 = p_Val2_10_fu_1973_p2.read().range(24, 10);
        tmp_18_reg_2679 = p_Val2_12_fu_2011_p2.read().range(20, 10);
        tmp_24_reg_2684 = ap_port_reg_data_16_V_read.read().range(17, 3);
        tmp_2_reg_2664 = p_Val2_4_fu_1901_p2.read().range(24, 10);
        tmp_33_reg_2814 = grp_fu_413_p2.read().range(26, 10);
        tmp_35_reg_2714 = p_Val2_26_fu_2109_p2.read().range(25, 10);
        tmp_3_5_reg_2804 = grp_fu_407_p2.read().range(27, 10);
        tmp_45_reg_2689 = p_Val2_17_fu_2049_p2.read().range(21, 10);
        tmp_5_reg_2659 = p_Val2_s_fu_1861_p2.read().range(24, 10);
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_port_reg_data_0_V_read = data_0_V_read.read();
        ap_port_reg_data_11_V_read = data_11_V_read.read();
        ap_port_reg_data_13_V_read = data_13_V_read.read();
        ap_port_reg_data_16_V_read = data_16_V_read.read();
        ap_port_reg_data_19_V_read = data_19_V_read.read();
        ap_port_reg_data_24_V_read = data_24_V_read.read();
        ap_port_reg_data_25_V_read = data_25_V_read.read();
        ap_port_reg_data_26_V_read = data_26_V_read.read();
        ap_port_reg_data_27_V_read = data_27_V_read.read();
        ap_port_reg_data_28_V_read = data_28_V_read.read();
        ap_port_reg_data_29_V_read = data_29_V_read.read();
        ap_port_reg_data_2_V_read = data_2_V_read.read();
        ap_port_reg_data_30_V_read = data_30_V_read.read();
        ap_port_reg_data_31_V_read = data_31_V_read.read();
        ap_port_reg_data_4_V_read = data_4_V_read.read();
        ap_port_reg_data_6_V_read = data_6_V_read.read();
    }
    if (((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        reg_1745 = grp_fu_408_p2.read().range(26, 10);
        reg_1749 = grp_fu_404_p2.read().range(25, 10);
        reg_1753 = grp_fu_409_p2.read().range(27, 10);
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        tmp17_reg_2799 = tmp17_fu_2295_p2.read();
        tmp21_reg_2839 = tmp21_fu_2510_p2.read();
        tmp31_reg_2844 = tmp31_fu_2548_p2.read();
        tmp_12_reg_2759 = grp_fu_405_p2.read().range(26, 10);
        tmp_20_reg_2774 = grp_fu_411_p2.read().range(26, 10);
        tmp_29_reg_2789 = grp_fu_416_p2.read().range(26, 10);
        tmp_3_2_reg_2739 = p_Val2_1_fu_2172_p2.read().range(27, 10);
        tmp_3_3_reg_2794 = grp_fu_402_p2.read().range(27, 10);
        tmp_3_7_reg_2754 = grp_fu_410_p2.read().range(27, 10);
        tmp_3_9_reg_2764 = grp_fu_406_p2.read().range(27, 10);
        tmp_3_s_reg_2769 = grp_fu_414_p2.read().range(27, 10);
        tmp_4_reg_2749 = grp_fu_417_p2.read().range(26, 10);
        tmp_8_reg_2734 = grp_fu_403_p2.read().range(26, 10);
        tmp_s_reg_2744 = tmp_s_fu_2188_p1.read().range(26, 10);
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        tmp_25_reg_2779 = grp_fu_412_p2.read().range(23, 10);
        tmp_27_reg_2784 = grp_fu_415_p2.read().range(25, 10);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        tmp_31_reg_2809 = grp_fu_415_p2.read().range(25, 10);
    }
}

void compute_layer_0_0_0_1::thread_OP1_V_10_cast_fu_1957_p1() {
    OP1_V_10_cast_fu_1957_p1 = esl_sext<25,18>(ap_port_reg_data_11_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_12_cast_fu_1989_p1() {
    OP1_V_12_cast_fu_1989_p1 = esl_sext<21,18>(ap_port_reg_data_13_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_14_cast_fu_1802_p1() {
    OP1_V_14_cast_fu_1802_p1 = esl_sext<26,18>(data_15_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_16_cast_fu_1807_p1() {
    OP1_V_16_cast_fu_1807_p1 = esl_sext<24,18>(data_17_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_17_cast_fu_1812_p1() {
    OP1_V_17_cast_fu_1812_p1 = esl_sext<28,18>(data_18_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_19_cast_fu_1817_p1() {
    OP1_V_19_cast_fu_1817_p1 = esl_sext<25,18>(data_20_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_20_cast_fu_1822_p1() {
    OP1_V_20_cast_fu_1822_p1 = esl_sext<26,18>(data_21_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_23_cast_fu_2065_p1() {
    OP1_V_23_cast_fu_2065_p1 = esl_sext<28,18>(ap_port_reg_data_24_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_24_cast_fu_2070_p1() {
    OP1_V_24_cast_fu_2070_p1 = esl_sext<28,18>(ap_port_reg_data_25_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_25_cast_fu_2075_p1() {
    OP1_V_25_cast_fu_2075_p1 = esl_sext<26,18>(ap_port_reg_data_26_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_26_cast_fu_2080_p1() {
    OP1_V_26_cast_fu_2080_p1 = esl_sext<27,18>(ap_port_reg_data_27_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_28_cast_fu_2125_p1() {
    OP1_V_28_cast_fu_2125_p1 = esl_sext<26,18>(ap_port_reg_data_29_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_29_cast_fu_2130_p1() {
    OP1_V_29_cast_fu_2130_p1 = esl_sext<27,18>(ap_port_reg_data_30_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_30_cast_fu_2135_p1() {
    OP1_V_30_cast_fu_2135_p1 = esl_sext<24,18>(ap_port_reg_data_31_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_3_cast_fu_1762_p1() {
    OP1_V_3_cast_fu_1762_p1 = esl_sext<27,18>(data_3_V_read.read());
}

void compute_layer_0_0_0_1::thread_OP1_V_cast_fu_1787_p1() {
    OP1_V_cast_fu_1787_p1 = esl_sext<27,18>(data_10_V_read.read());
}

void compute_layer_0_0_0_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(0, 0);
}

void compute_layer_0_0_0_1::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read().range(1, 1);
}

void compute_layer_0_0_0_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void compute_layer_0_0_0_1::thread_ap_enable_reg_pp0_iter0() {
    if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
        ap_enable_reg_pp0_iter0 = ap_start.read();
    } else {
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_preg.read();
    }
}

void compute_layer_0_0_0_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void compute_layer_0_0_0_1::thread_ap_pipeline_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_pipeline_idle_pp0 = ap_const_logic_1;
    } else {
        ap_pipeline_idle_pp0 = ap_const_logic_0;
    }
}

void compute_layer_0_0_0_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void compute_layer_0_0_0_1::thread_ap_return() {
    ap_return = (!tmp30_fu_2562_p2.read().is_01() || !tmp15_fu_2554_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp30_fu_2562_p2.read()) + sc_biguint<18>(tmp15_fu_2554_p2.read()));
}

void compute_layer_0_0_0_1::thread_grp_fu_1715_p4() {
    grp_fu_1715_p4 = grp_fu_412_p2.read().range(23, 10);
}

void compute_layer_0_0_0_1::thread_grp_fu_402_p1() {
    grp_fu_402_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFED4);
}

void compute_layer_0_0_0_1::thread_grp_fu_403_p1() {
    grp_fu_403_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF71);
}

void compute_layer_0_0_0_1::thread_grp_fu_404_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_404_p0 =  (sc_lv<18>) (OP1_V_28_cast_fu_2125_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_404_p0 =  (sc_lv<18>) (OP1_V_14_cast_fu_1802_p1.read());
        } else {
            grp_fu_404_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_404_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_404_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_404_p1 =  (sc_lv<9>) (ap_const_lv26_3FFFF97);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_404_p1 =  (sc_lv<9>) (ap_const_lv26_5C);
        } else {
            grp_fu_404_p1 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        grp_fu_404_p1 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_405_p1() {
    grp_fu_405_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF52);
}

void compute_layer_0_0_0_1::thread_grp_fu_406_p1() {
    grp_fu_406_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFEB3);
}

void compute_layer_0_0_0_1::thread_grp_fu_407_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_407_p0 =  (sc_lv<18>) (OP1_V_24_cast_fu_2070_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_407_p0 =  (sc_lv<18>) (OP1_V_3_cast_fu_1762_p1.read());
        } else {
            grp_fu_407_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_407_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_407_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_407_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE87);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_407_p1 =  (sc_lv<10>) (ap_const_lv27_7FFFF4B);
        } else {
            grp_fu_407_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        grp_fu_407_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_408_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_408_p0 =  (sc_lv<18>) (OP1_V_29_cast_fu_2130_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_408_p0 =  (sc_lv<18>) (OP1_V_cast_fu_1787_p1.read());
        } else {
            grp_fu_408_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_408_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_408_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_408_p1 =  (sc_lv<10>) (ap_const_lv27_7FFFF46);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_408_p1 =  (sc_lv<10>) (ap_const_lv27_F2);
        } else {
            grp_fu_408_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        grp_fu_408_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_409_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_409_p0 =  (sc_lv<18>) (OP1_V_23_cast_fu_2065_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_409_p0 =  (sc_lv<18>) (OP1_V_17_cast_fu_1812_p1.read());
        } else {
            grp_fu_409_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_409_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_409_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_409_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFEB6);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_409_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE4A);
        } else {
            grp_fu_409_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        grp_fu_409_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_410_p1() {
    grp_fu_410_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE92);
}

void compute_layer_0_0_0_1::thread_grp_fu_411_p1() {
    grp_fu_411_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF5C);
}

void compute_layer_0_0_0_1::thread_grp_fu_412_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_412_p0 =  (sc_lv<18>) (OP1_V_30_cast_fu_2135_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_412_p0 =  (sc_lv<18>) (OP1_V_16_cast_fu_1807_p1.read());
        } else {
            grp_fu_412_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_412_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_412_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_412_p1 =  (sc_lv<6>) (ap_const_lv24_1D);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_412_p1 =  (sc_lv<6>) (ap_const_lv24_19);
        } else {
            grp_fu_412_p1 =  (sc_lv<6>) ("XXXXXX");
        }
    } else {
        grp_fu_412_p1 =  (sc_lv<6>) ("XXXXXX");
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_413_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_413_p0 =  (sc_lv<18>) (OP1_V_26_cast_fu_2080_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_413_p0 =  (sc_lv<18>) (OP1_V_19_cast_fu_1817_p1.read());
        } else {
            grp_fu_413_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_413_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_413_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_413_p1 =  (sc_lv<9>) (ap_const_lv27_9F);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_413_p1 =  (sc_lv<9>) (ap_const_lv25_32);
        } else {
            grp_fu_413_p1 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        grp_fu_413_p1 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_414_p1() {
    grp_fu_414_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE73);
}

void compute_layer_0_0_0_1::thread_grp_fu_415_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_415_p0 =  (sc_lv<18>) (OP1_V_25_cast_fu_2075_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_415_p0 =  (sc_lv<18>) (OP1_V_20_cast_fu_1822_p1.read());
        } else {
            grp_fu_415_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_415_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_415_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_415_p1 =  (sc_lv<9>) (ap_const_lv26_4A);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_415_p1 =  (sc_lv<9>) (ap_const_lv26_3FFFF9F);
        } else {
            grp_fu_415_p1 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        grp_fu_415_p1 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_layer_0_0_0_1::thread_grp_fu_416_p1() {
    grp_fu_416_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF0B);
}

void compute_layer_0_0_0_1::thread_grp_fu_417_p1() {
    grp_fu_417_p1 =  (sc_lv<9>) (ap_const_lv27_BF);
}

void compute_layer_0_0_0_1::thread_p_Val2_10_fu_1973_p2() {
    p_Val2_10_fu_1973_p2 = (!p_shl4_cast_fu_1969_p1.read().is_01() || !OP1_V_10_cast_fu_1957_p1.read().is_01())? sc_lv<25>(): (sc_bigint<25>(p_shl4_cast_fu_1969_p1.read()) + sc_bigint<25>(OP1_V_10_cast_fu_1957_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_Val2_12_fu_2011_p2() {
    p_Val2_12_fu_2011_p2 = (!p_neg_fu_2005_p2.read().is_01() || !OP1_V_12_cast_fu_1989_p1.read().is_01())? sc_lv<21>(): (sc_biguint<21>(p_neg_fu_2005_p2.read()) - sc_bigint<21>(OP1_V_12_cast_fu_1989_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_Val2_17_fu_2049_p2() {
    p_Val2_17_fu_2049_p2 = (!ap_const_lv22_0.is_01() || !p_shl2_cast_fu_2045_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_0) - sc_bigint<22>(p_shl2_cast_fu_2045_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_Val2_1_fu_2172_p2() {
    p_Val2_1_fu_2172_p2 = (!p_shl11_cast_fu_2168_p1.read().is_01() || !p_shl9_cast_fu_2157_p1.read().is_01())? sc_lv<28>(): (sc_bigint<28>(p_shl11_cast_fu_2168_p1.read()) - sc_bigint<28>(p_shl9_cast_fu_2157_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_Val2_26_fu_2109_p2() {
    p_Val2_26_fu_2109_p2 = (!p_shl_cast_fu_2093_p1.read().is_01() || !p_shl1_cast_fu_2105_p1.read().is_01())? sc_lv<26>(): (sc_bigint<26>(p_shl_cast_fu_2093_p1.read()) - sc_bigint<26>(p_shl1_cast_fu_2105_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_Val2_4_fu_1901_p2() {
    p_Val2_4_fu_1901_p2 = (!p_shl7_cast_fu_1885_p1.read().is_01() || !p_shl8_cast_fu_1897_p1.read().is_01())? sc_lv<25>(): (sc_bigint<25>(p_shl7_cast_fu_1885_p1.read()) + sc_bigint<25>(p_shl8_cast_fu_1897_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_Val2_6_fu_1941_p2() {
    p_Val2_6_fu_1941_p2 = (!p_shl5_cast_fu_1925_p1.read().is_01() || !p_shl6_cast_fu_1937_p1.read().is_01())? sc_lv<26>(): (sc_bigint<26>(p_shl5_cast_fu_1925_p1.read()) + sc_bigint<26>(p_shl6_cast_fu_1937_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_Val2_s_fu_1861_p2() {
    p_Val2_s_fu_1861_p2 = (!p_shl14_cast_fu_1857_p1.read().is_01() || !p_shl12_cast_fu_1845_p1.read().is_01())? sc_lv<25>(): (sc_bigint<25>(p_shl14_cast_fu_1857_p1.read()) - sc_bigint<25>(p_shl12_cast_fu_1845_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_neg_fu_2005_p2() {
    p_neg_fu_2005_p2 = (!ap_const_lv21_0.is_01() || !p_shl3_cast_fu_2001_p1.read().is_01())? sc_lv<21>(): (sc_biguint<21>(ap_const_lv21_0) - sc_bigint<21>(p_shl3_cast_fu_2001_p1.read()));
}

void compute_layer_0_0_0_1::thread_p_shl10_fu_1837_p3() {
    p_shl10_fu_1837_p3 = esl_concat<18,6>(ap_port_reg_data_0_V_read.read(), ap_const_lv6_0);
}

void compute_layer_0_0_0_1::thread_p_shl11_cast_fu_2168_p1() {
    p_shl11_cast_fu_2168_p1 = esl_sext<28,24>(p_shl11_fu_2161_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl11_fu_2161_p3() {
    p_shl11_fu_2161_p3 = esl_concat<18,6>(data_2_V_read_2_reg_2653.read(), ap_const_lv6_0);
}

void compute_layer_0_0_0_1::thread_p_shl12_cast_fu_1845_p1() {
    p_shl12_cast_fu_1845_p1 = esl_sext<25,24>(p_shl10_fu_1837_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl12_fu_1849_p3() {
    p_shl12_fu_1849_p3 = esl_concat<18,2>(ap_port_reg_data_0_V_read.read(), ap_const_lv2_0);
}

void compute_layer_0_0_0_1::thread_p_shl14_cast_fu_1857_p1() {
    p_shl14_cast_fu_1857_p1 = esl_sext<25,20>(p_shl12_fu_1849_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl1_cast_fu_2105_p1() {
    p_shl1_cast_fu_2105_p1 = esl_sext<26,21>(p_shl1_fu_2097_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl1_fu_2097_p3() {
    p_shl1_fu_2097_p3 = esl_concat<18,3>(ap_port_reg_data_28_V_read.read(), ap_const_lv3_0);
}

void compute_layer_0_0_0_1::thread_p_shl2_cast_fu_2045_p1() {
    p_shl2_cast_fu_2045_p1 = esl_sext<22,21>(p_shl2_fu_2037_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl2_fu_2037_p3() {
    p_shl2_fu_2037_p3 = esl_concat<18,3>(ap_port_reg_data_19_V_read.read(), ap_const_lv3_0);
}

void compute_layer_0_0_0_1::thread_p_shl3_cast_fu_2001_p1() {
    p_shl3_cast_fu_2001_p1 = esl_sext<21,20>(p_shl3_fu_1993_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl3_fu_1993_p3() {
    p_shl3_fu_1993_p3 = esl_concat<18,2>(ap_port_reg_data_13_V_read.read(), ap_const_lv2_0);
}

void compute_layer_0_0_0_1::thread_p_shl4_cast_fu_1969_p1() {
    p_shl4_cast_fu_1969_p1 = esl_sext<25,24>(p_shl4_fu_1961_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl4_fu_1961_p3() {
    p_shl4_fu_1961_p3 = esl_concat<18,6>(ap_port_reg_data_11_V_read.read(), ap_const_lv6_0);
}

void compute_layer_0_0_0_1::thread_p_shl5_cast_fu_1925_p1() {
    p_shl5_cast_fu_1925_p1 = esl_sext<26,25>(p_shl5_fu_1917_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl5_fu_1917_p3() {
    p_shl5_fu_1917_p3 = esl_concat<18,7>(ap_port_reg_data_6_V_read.read(), ap_const_lv7_0);
}

void compute_layer_0_0_0_1::thread_p_shl6_cast_fu_1937_p1() {
    p_shl6_cast_fu_1937_p1 = esl_sext<26,23>(p_shl6_fu_1929_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl6_fu_1929_p3() {
    p_shl6_fu_1929_p3 = esl_concat<18,5>(ap_port_reg_data_6_V_read.read(), ap_const_lv5_0);
}

void compute_layer_0_0_0_1::thread_p_shl7_cast_fu_1885_p1() {
    p_shl7_cast_fu_1885_p1 = esl_sext<25,24>(p_shl7_fu_1877_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl7_fu_1877_p3() {
    p_shl7_fu_1877_p3 = esl_concat<18,6>(ap_port_reg_data_4_V_read.read(), ap_const_lv6_0);
}

void compute_layer_0_0_0_1::thread_p_shl8_cast_fu_1897_p1() {
    p_shl8_cast_fu_1897_p1 = esl_sext<25,19>(p_shl8_fu_1889_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl8_fu_1889_p3() {
    p_shl8_fu_1889_p3 = esl_concat<18,1>(ap_port_reg_data_4_V_read.read(), ap_const_lv1_0);
}

void compute_layer_0_0_0_1::thread_p_shl9_cast_fu_2157_p1() {
    p_shl9_cast_fu_2157_p1 = esl_sext<28,27>(p_shl9_fu_2150_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl9_fu_2150_p3() {
    p_shl9_fu_2150_p3 = esl_concat<18,9>(data_2_V_read_2_reg_2653.read(), ap_const_lv9_0);
}

void compute_layer_0_0_0_1::thread_p_shl_cast_fu_2093_p1() {
    p_shl_cast_fu_2093_p1 = esl_sext<26,25>(p_shl_fu_2085_p3.read());
}

void compute_layer_0_0_0_1::thread_p_shl_fu_2085_p3() {
    p_shl_fu_2085_p3 = esl_concat<18,7>(ap_port_reg_data_28_V_read.read(), ap_const_lv7_0);
}

void compute_layer_0_0_0_1::thread_tmp10_fu_2420_p2() {
    tmp10_fu_2420_p2 = (!tmp9_fu_2414_p2.read().is_01() || !tmp8_fu_2409_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp9_fu_2414_p2.read()) + sc_biguint<18>(tmp8_fu_2409_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp11_fu_2426_p2() {
    tmp11_fu_2426_p2 = (!tmp_3_s_reg_2769.read().is_01() || !tmp_19_fu_2329_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_3_s_reg_2769.read()) + sc_bigint<18>(tmp_19_fu_2329_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp12_fu_2431_p2() {
    tmp12_fu_2431_p2 = (!tmp_21_fu_2332_p1.read().is_01() || !tmp_23_fu_2335_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_21_fu_2332_p1.read()) + sc_bigint<18>(tmp_23_fu_2335_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp13_fu_2437_p2() {
    tmp13_fu_2437_p2 = (!tmp12_fu_2431_p2.read().is_01() || !tmp11_fu_2426_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp12_fu_2431_p2.read()) + sc_biguint<18>(tmp11_fu_2426_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp14_fu_2443_p2() {
    tmp14_fu_2443_p2 = (!tmp13_fu_2437_p2.read().is_01() || !tmp10_fu_2420_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp13_fu_2437_p2.read()) + sc_biguint<18>(tmp10_fu_2420_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp15_fu_2554_p2() {
    tmp15_fu_2554_p2 = (!tmp14_reg_2824.read().is_01() || !tmp7_reg_2819.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp14_reg_2824.read()) + sc_biguint<18>(tmp7_reg_2819.read()));
}

void compute_layer_0_0_0_1::thread_tmp16_fu_2449_p2() {
    tmp16_fu_2449_p2 = (!tmp_26_fu_2342_p1.read().is_01() || !reg_1753.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_26_fu_2342_p1.read()) + sc_biguint<18>(reg_1753.read()));
}

void compute_layer_0_0_0_1::thread_tmp17_cast_fu_2455_p1() {
    tmp17_cast_fu_2455_p1 = esl_sext<18,16>(tmp17_reg_2799.read());
}

void compute_layer_0_0_0_1::thread_tmp17_fu_2295_p2() {
    tmp17_fu_2295_p2 = (!tmp_28_cast_fu_2258_p1.read().is_01() || !tmp_30_cast_fu_2271_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_28_cast_fu_2258_p1.read()) + sc_bigint<16>(tmp_30_cast_fu_2271_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp18_fu_2458_p2() {
    tmp18_fu_2458_p2 = (!tmp17_cast_fu_2455_p1.read().is_01() || !tmp16_fu_2449_p2.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp17_cast_fu_2455_p1.read()) + sc_biguint<18>(tmp16_fu_2449_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp19_fu_2499_p2() {
    tmp19_fu_2499_p2 = (!tmp_28_fu_2476_p1.read().is_01() || !tmp_30_fu_2479_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_28_fu_2476_p1.read()) + sc_bigint<18>(tmp_30_fu_2479_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp1_fu_2369_p2() {
    tmp1_fu_2369_p2 = (!tmp_6_fu_2301_p1.read().is_01() || !tmp_9_fu_2304_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_6_fu_2301_p1.read()) + sc_bigint<18>(tmp_9_fu_2304_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp20_fu_2505_p2() {
    tmp20_fu_2505_p2 = (!tmp_3_3_reg_2794.read().is_01() || !reg_1753.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_3_3_reg_2794.read()) + sc_biguint<18>(reg_1753.read()));
}

void compute_layer_0_0_0_1::thread_tmp21_fu_2510_p2() {
    tmp21_fu_2510_p2 = (!tmp20_fu_2505_p2.read().is_01() || !tmp19_fu_2499_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp20_fu_2505_p2.read()) + sc_biguint<18>(tmp19_fu_2499_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp22_fu_2558_p2() {
    tmp22_fu_2558_p2 = (!tmp21_reg_2839.read().is_01() || !tmp18_reg_2829.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp21_reg_2839.read()) + sc_biguint<18>(tmp18_reg_2829.read()));
}

void compute_layer_0_0_0_1::thread_tmp23_fu_2516_p2() {
    tmp23_fu_2516_p2 = (!tmp_3_5_reg_2804.read().is_01() || !tmp_32_fu_2482_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_3_5_reg_2804.read()) + sc_bigint<18>(tmp_32_fu_2482_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp24_fu_2521_p2() {
    tmp24_fu_2521_p2 = (!tmp_34_fu_2485_p1.read().is_01() || !tmp_36_fu_2488_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_34_fu_2485_p1.read()) + sc_bigint<18>(tmp_36_fu_2488_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp25_fu_2527_p2() {
    tmp25_fu_2527_p2 = (!tmp24_fu_2521_p2.read().is_01() || !tmp23_fu_2516_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp24_fu_2521_p2.read()) + sc_biguint<18>(tmp23_fu_2516_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp26_fu_2533_p2() {
    tmp26_fu_2533_p2 = (!tmp_38_fu_2491_p1.read().is_01() || !tmp_40_fu_2495_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_38_fu_2491_p1.read()) + sc_bigint<18>(tmp_40_fu_2495_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp27_fu_2464_p2() {
    tmp27_fu_2464_p2 = (!tmp_3_15_cast_fu_2339_p1.read().is_01() || !ap_const_lv16_FF86.is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_3_15_cast_fu_2339_p1.read()) + sc_bigint<16>(ap_const_lv16_FF86));
}

void compute_layer_0_0_0_1::thread_tmp28_cast_fu_2539_p1() {
    tmp28_cast_fu_2539_p1 = esl_sext<18,16>(tmp28_reg_2834.read());
}

void compute_layer_0_0_0_1::thread_tmp28_fu_2470_p2() {
    tmp28_fu_2470_p2 = (!tmp27_fu_2464_p2.read().is_01() || !tmp_46_cast_fu_2365_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp27_fu_2464_p2.read()) + sc_bigint<16>(tmp_46_cast_fu_2365_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp29_fu_2542_p2() {
    tmp29_fu_2542_p2 = (!tmp28_cast_fu_2539_p1.read().is_01() || !tmp26_fu_2533_p2.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp28_cast_fu_2539_p1.read()) + sc_biguint<18>(tmp26_fu_2533_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp2_fu_2375_p2() {
    tmp2_fu_2375_p2 = (!tmp_3_2_reg_2739.read().is_01() || !tmp_1_fu_2307_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_3_2_reg_2739.read()) + sc_bigint<18>(tmp_1_fu_2307_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp30_fu_2562_p2() {
    tmp30_fu_2562_p2 = (!tmp31_reg_2844.read().is_01() || !tmp22_fu_2558_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp31_reg_2844.read()) + sc_biguint<18>(tmp22_fu_2558_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp31_fu_2548_p2() {
    tmp31_fu_2548_p2 = (!tmp29_fu_2542_p2.read().is_01() || !tmp25_fu_2527_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp29_fu_2542_p2.read()) + sc_biguint<18>(tmp25_fu_2527_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp3_fu_2380_p2() {
    tmp3_fu_2380_p2 = (!tmp2_fu_2375_p2.read().is_01() || !tmp1_fu_2369_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp2_fu_2375_p2.read()) + sc_biguint<18>(tmp1_fu_2369_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp4_fu_2386_p2() {
    tmp4_fu_2386_p2 = (!tmp_3_fu_2310_p1.read().is_01() || !tmp_7_fu_2313_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_3_fu_2310_p1.read()) + sc_bigint<18>(tmp_7_fu_2313_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp5_fu_2392_p2() {
    tmp5_fu_2392_p2 = (!tmp_11_fu_2316_p1.read().is_01() || !tmp_3_7_reg_2754.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_11_fu_2316_p1.read()) + sc_biguint<18>(tmp_3_7_reg_2754.read()));
}

void compute_layer_0_0_0_1::thread_tmp6_fu_2397_p2() {
    tmp6_fu_2397_p2 = (!tmp5_fu_2392_p2.read().is_01() || !tmp4_fu_2386_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp5_fu_2392_p2.read()) + sc_biguint<18>(tmp4_fu_2386_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp7_fu_2403_p2() {
    tmp7_fu_2403_p2 = (!tmp6_fu_2397_p2.read().is_01() || !tmp3_fu_2380_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp6_fu_2397_p2.read()) + sc_biguint<18>(tmp3_fu_2380_p2.read()));
}

void compute_layer_0_0_0_1::thread_tmp8_fu_2409_p2() {
    tmp8_fu_2409_p2 = (!tmp_13_fu_2319_p1.read().is_01() || !tmp_3_9_reg_2764.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_13_fu_2319_p1.read()) + sc_biguint<18>(tmp_3_9_reg_2764.read()));
}

void compute_layer_0_0_0_1::thread_tmp9_fu_2414_p2() {
    tmp9_fu_2414_p2 = (!tmp_15_fu_2322_p1.read().is_01() || !tmp_17_fu_2326_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_15_fu_2322_p1.read()) + sc_bigint<18>(tmp_17_fu_2326_p1.read()));
}

void compute_layer_0_0_0_1::thread_tmp_11_fu_2316_p1() {
    tmp_11_fu_2316_p1 = esl_sext<18,16>(tmp_10_reg_2669.read());
}

void compute_layer_0_0_0_1::thread_tmp_13_fu_2319_p1() {
    tmp_13_fu_2319_p1 = esl_sext<18,17>(tmp_12_reg_2759.read());
}

void compute_layer_0_0_0_1::thread_tmp_15_fu_2322_p1() {
    tmp_15_fu_2322_p1 = esl_sext<18,17>(reg_1745.read());
}

void compute_layer_0_0_0_1::thread_tmp_17_fu_2326_p1() {
    tmp_17_fu_2326_p1 = esl_sext<18,15>(tmp_16_reg_2674.read());
}

void compute_layer_0_0_0_1::thread_tmp_19_fu_2329_p1() {
    tmp_19_fu_2329_p1 = esl_sext<18,11>(tmp_18_reg_2679.read());
}

void compute_layer_0_0_0_1::thread_tmp_1_fu_2307_p1() {
    tmp_1_fu_2307_p1 = esl_sext<18,17>(tmp_s_reg_2744.read());
}

void compute_layer_0_0_0_1::thread_tmp_21_fu_2332_p1() {
    tmp_21_fu_2332_p1 = esl_sext<18,17>(tmp_20_reg_2774.read());
}

void compute_layer_0_0_0_1::thread_tmp_23_fu_2335_p1() {
    tmp_23_fu_2335_p1 = esl_sext<18,16>(reg_1749.read());
}

void compute_layer_0_0_0_1::thread_tmp_26_fu_2342_p1() {
    tmp_26_fu_2342_p1 = esl_sext<18,14>(tmp_25_reg_2779.read());
}

void compute_layer_0_0_0_1::thread_tmp_28_cast_fu_2258_p1() {
    tmp_28_cast_fu_2258_p1 = esl_sext<16,12>(tmp_45_reg_2689.read());
}

void compute_layer_0_0_0_1::thread_tmp_28_fu_2476_p1() {
    tmp_28_fu_2476_p1 = esl_sext<18,16>(tmp_27_reg_2784.read());
}

void compute_layer_0_0_0_1::thread_tmp_30_cast_fu_2271_p1() {
    tmp_30_cast_fu_2271_p1 = esl_sext<16,15>(tmp_46_fu_2261_p4.read());
}

void compute_layer_0_0_0_1::thread_tmp_30_fu_2479_p1() {
    tmp_30_fu_2479_p1 = esl_sext<18,17>(tmp_29_reg_2789.read());
}

void compute_layer_0_0_0_1::thread_tmp_32_fu_2482_p1() {
    tmp_32_fu_2482_p1 = esl_sext<18,16>(tmp_31_reg_2809.read());
}

void compute_layer_0_0_0_1::thread_tmp_34_fu_2485_p1() {
    tmp_34_fu_2485_p1 = esl_sext<18,17>(tmp_33_reg_2814.read());
}

void compute_layer_0_0_0_1::thread_tmp_36_fu_2488_p1() {
    tmp_36_fu_2488_p1 = esl_sext<18,16>(ap_pipeline_reg_pp0_iter1_tmp_35_reg_2714.read());
}

void compute_layer_0_0_0_1::thread_tmp_38_fu_2491_p1() {
    tmp_38_fu_2491_p1 = esl_sext<18,16>(reg_1749.read());
}

void compute_layer_0_0_0_1::thread_tmp_3_15_cast_fu_2339_p1() {
    tmp_3_15_cast_fu_2339_p1 = esl_sext<16,15>(tmp_24_reg_2684.read());
}

void compute_layer_0_0_0_1::thread_tmp_3_fu_2310_p1() {
    tmp_3_fu_2310_p1 = esl_sext<18,15>(tmp_2_reg_2664.read());
}

void compute_layer_0_0_0_1::thread_tmp_40_fu_2495_p1() {
    tmp_40_fu_2495_p1 = esl_sext<18,17>(reg_1745.read());
}

void compute_layer_0_0_0_1::thread_tmp_46_cast_fu_2365_p1() {
    tmp_46_cast_fu_2365_p1 = esl_sext<16,14>(grp_fu_1715_p4.read());
}

void compute_layer_0_0_0_1::thread_tmp_46_fu_2261_p1() {
    tmp_46_fu_2261_p1 =  (sc_lv<25>) (grp_fu_413_p2.read());
}

void compute_layer_0_0_0_1::thread_tmp_46_fu_2261_p4() {
    tmp_46_fu_2261_p4 = tmp_46_fu_2261_p1.read().range(24, 10);
}

void compute_layer_0_0_0_1::thread_tmp_6_fu_2301_p1() {
    tmp_6_fu_2301_p1 = esl_sext<18,15>(tmp_5_reg_2659.read());
}

void compute_layer_0_0_0_1::thread_tmp_7_fu_2313_p1() {
    tmp_7_fu_2313_p1 = esl_sext<18,17>(tmp_4_reg_2749.read());
}

void compute_layer_0_0_0_1::thread_tmp_9_fu_2304_p1() {
    tmp_9_fu_2304_p1 = esl_sext<18,17>(tmp_8_reg_2734.read());
}

void compute_layer_0_0_0_1::thread_tmp_s_fu_2188_p1() {
    tmp_s_fu_2188_p1 =  (sc_lv<27>) (grp_fu_407_p2.read());
}

void compute_layer_0_0_0_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

}

