// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _myproject_HH_
#define _myproject_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "compute_layer_0_0_0_s.h"
#include "compute_layer_0_0_0_1.h"
#include "relu.h"
#include "sigmoid.h"

namespace ap_rtl {

struct myproject : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<18> > data_0_V;
    sc_in< sc_lv<18> > data_1_V;
    sc_in< sc_lv<18> > data_2_V;
    sc_in< sc_lv<18> > data_3_V;
    sc_in< sc_lv<18> > data_4_V;
    sc_in< sc_lv<18> > data_5_V;
    sc_in< sc_lv<18> > data_6_V;
    sc_in< sc_lv<18> > data_7_V;
    sc_in< sc_lv<18> > data_8_V;
    sc_in< sc_lv<18> > data_9_V;
    sc_out< sc_lv<18> > res_0_V;
    sc_out< sc_logic > res_0_V_ap_vld;
    sc_out< sc_lv<16> > const_size_in;
    sc_out< sc_logic > const_size_in_ap_vld;
    sc_out< sc_lv<16> > const_size_out;
    sc_out< sc_logic > const_size_out_ap_vld;


    // Module declarations
    myproject(sc_module_name name);
    SC_HAS_PROCESS(myproject);

    ~myproject();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    compute_layer_0_0_0_s* grp_compute_layer_0_0_0_s_fu_143;
    compute_layer_0_0_0_1* grp_compute_layer_0_0_0_1_fu_167;
    relu* call_ret2_relu_fu_203;
    sigmoid* grp_sigmoid_fu_239;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter6;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter7;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_lv<18> > logits1_0_V_reg_517;
    sc_signal< sc_lv<18> > logits1_1_V_reg_522;
    sc_signal< sc_lv<18> > logits1_2_V_reg_527;
    sc_signal< sc_lv<18> > logits1_3_V_reg_532;
    sc_signal< sc_lv<18> > logits1_4_V_reg_537;
    sc_signal< sc_lv<18> > logits1_5_V_reg_542;
    sc_signal< sc_lv<18> > logits1_6_V_reg_547;
    sc_signal< sc_lv<18> > logits1_7_V_reg_552;
    sc_signal< sc_lv<18> > logits1_8_V_reg_557;
    sc_signal< sc_lv<18> > logits1_9_V_reg_562;
    sc_signal< sc_lv<18> > logits1_10_V_reg_567;
    sc_signal< sc_lv<18> > logits1_11_V_reg_572;
    sc_signal< sc_lv<18> > logits1_12_V_reg_577;
    sc_signal< sc_lv<18> > logits1_13_V_reg_582;
    sc_signal< sc_lv<18> > logits1_14_V_reg_587;
    sc_signal< sc_lv<18> > logits1_15_V_reg_592;
    sc_signal< sc_lv<18> > logits1_16_V_reg_597;
    sc_signal< sc_lv<18> > logits1_17_V_reg_602;
    sc_signal< sc_lv<18> > logits1_18_V_reg_607;
    sc_signal< sc_lv<18> > logits1_19_V_reg_612;
    sc_signal< sc_lv<18> > logits1_20_V_reg_617;
    sc_signal< sc_lv<18> > logits1_21_V_reg_622;
    sc_signal< sc_lv<18> > logits1_22_V_reg_627;
    sc_signal< sc_lv<18> > logits1_23_V_reg_632;
    sc_signal< sc_lv<18> > logits1_24_V_reg_637;
    sc_signal< sc_lv<18> > logits1_25_V_reg_642;
    sc_signal< sc_lv<18> > logits1_26_V_reg_647;
    sc_signal< sc_lv<18> > logits1_27_V_reg_652;
    sc_signal< sc_lv<18> > logits1_28_V_reg_657;
    sc_signal< sc_lv<18> > logits1_29_V_reg_662;
    sc_signal< sc_lv<18> > logits1_30_V_reg_667;
    sc_signal< sc_lv<18> > logits1_31_V_reg_672;
    sc_signal< sc_lv<18> > layer1_out_0_V_reg_677;
    sc_signal< sc_lv<18> > layer1_out_1_V_reg_682;
    sc_signal< sc_lv<18> > layer1_out_2_V_reg_687;
    sc_signal< sc_lv<18> > layer1_out_3_V_reg_692;
    sc_signal< sc_lv<18> > layer1_out_4_V_reg_697;
    sc_signal< sc_lv<18> > layer1_out_5_V_reg_702;
    sc_signal< sc_lv<18> > layer1_out_6_V_reg_707;
    sc_signal< sc_lv<18> > layer1_out_7_V_reg_712;
    sc_signal< sc_lv<18> > layer1_out_8_V_reg_717;
    sc_signal< sc_lv<18> > layer1_out_9_V_reg_722;
    sc_signal< sc_lv<18> > layer1_out_10_V_reg_727;
    sc_signal< sc_lv<18> > layer1_out_11_V_reg_732;
    sc_signal< sc_lv<18> > layer1_out_12_V_reg_737;
    sc_signal< sc_lv<18> > layer1_out_13_V_reg_742;
    sc_signal< sc_lv<18> > layer1_out_14_V_reg_747;
    sc_signal< sc_lv<18> > layer1_out_15_V_reg_752;
    sc_signal< sc_lv<18> > layer1_out_16_V_reg_757;
    sc_signal< sc_lv<18> > layer1_out_17_V_reg_762;
    sc_signal< sc_lv<18> > layer1_out_18_V_reg_767;
    sc_signal< sc_lv<18> > layer1_out_19_V_reg_772;
    sc_signal< sc_lv<18> > layer1_out_20_V_reg_777;
    sc_signal< sc_lv<18> > layer1_out_21_V_reg_782;
    sc_signal< sc_lv<18> > layer1_out_22_V_reg_787;
    sc_signal< sc_lv<18> > layer1_out_23_V_reg_792;
    sc_signal< sc_lv<18> > layer1_out_24_V_reg_797;
    sc_signal< sc_lv<18> > layer1_out_25_V_reg_802;
    sc_signal< sc_lv<18> > layer1_out_26_V_reg_807;
    sc_signal< sc_lv<18> > layer1_out_27_V_reg_812;
    sc_signal< sc_lv<18> > layer1_out_28_V_reg_817;
    sc_signal< sc_lv<18> > layer1_out_29_V_reg_822;
    sc_signal< sc_lv<18> > layer1_out_30_V_reg_827;
    sc_signal< sc_lv<18> > layer1_out_31_V_reg_832;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_1_fu_167_ap_return;
    sc_signal< sc_lv<18> > logits2_0_V_reg_837;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0_preg;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_s_fu_143_ap_start;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_s_fu_143_ap_done;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_s_fu_143_ap_idle;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_s_fu_143_ap_ready;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_0;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_1;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_2;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_3;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_4;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_5;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_6;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_7;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_8;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_9;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_10;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_11;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_12;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_13;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_14;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_15;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_16;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_17;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_18;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_19;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_20;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_21;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_22;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_23;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_24;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_25;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_26;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_27;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_28;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_29;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_30;
    sc_signal< sc_lv<18> > grp_compute_layer_0_0_0_s_fu_143_ap_return_31;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_1_fu_167_ap_start;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_1_fu_167_ap_done;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_1_fu_167_ap_idle;
    sc_signal< sc_logic > grp_compute_layer_0_0_0_1_fu_167_ap_ready;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_0;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_1;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_2;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_3;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_4;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_5;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_6;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_7;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_8;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_9;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_10;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_11;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_12;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_13;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_14;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_15;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_16;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_17;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_18;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_19;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_20;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_21;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_22;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_23;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_24;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_25;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_26;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_27;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_28;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_29;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_30;
    sc_signal< sc_lv<18> > call_ret2_relu_fu_203_ap_return_31;
    sc_signal< sc_logic > grp_sigmoid_fu_239_ap_start;
    sc_signal< sc_logic > grp_sigmoid_fu_239_ap_done;
    sc_signal< sc_logic > grp_sigmoid_fu_239_ap_idle;
    sc_signal< sc_logic > grp_sigmoid_fu_239_ap_ready;
    sc_signal< sc_lv<10> > grp_sigmoid_fu_239_ap_return;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    sc_signal< sc_logic > ap_grp_compute_layer_0_0_0_s_fu_143_ap_start;
    sc_signal< sc_logic > ap_reg_grp_compute_layer_0_0_0_1_fu_167_ap_start;
    sc_signal< sc_logic > ap_reg_grp_sigmoid_fu_239_ap_start;
    sc_signal< sc_logic > ap_pipeline_idle_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_pp0_stage0;
    static const sc_lv<2> ap_ST_fsm_pp0_stage1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<16> ap_const_lv16_A;
    static const sc_lv<16> ap_const_lv16_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_done();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_grp_compute_layer_0_0_0_s_fu_143_ap_start();
    void thread_ap_idle();
    void thread_ap_pipeline_idle_pp0();
    void thread_ap_ready();
    void thread_const_size_in();
    void thread_const_size_in_ap_vld();
    void thread_const_size_out();
    void thread_const_size_out_ap_vld();
    void thread_grp_compute_layer_0_0_0_1_fu_167_ap_start();
    void thread_grp_compute_layer_0_0_0_s_fu_143_ap_start();
    void thread_grp_sigmoid_fu_239_ap_start();
    void thread_res_0_V();
    void thread_res_0_V_ap_vld();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
