on: 
  pull_request:
    branches: [main]
    types: [opened]

name: Create branch on PR opened
jobs:
  create-branch-on-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v2.2.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'pr/${{ github.event.pull_request.number }}'
        sha: '${{ github.event.pull_request.head.sha }}'
