on:
  pull_request:
    types: [opened]
    branches: [main]

name: Create branch on PR from fork
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v2.2.0
      if: github.event.pull_request.head.repo.full_name != github.repository
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'pr/${{ github.event.pull_request.number }}'
        sha: '${{ github.event.pull_request.head.sha }}'
