name: test-sphinx
on:
  pull_request:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ferdnyc/sphinx-action@controlled-apt
      with:
        docs-folder: "docs/"
        install: git
