name: test-sphinx
on:
  pull_request:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1    
    - uses: erpcya/sphinx-action@feature/#update-sphinx-base-image
      with:
        docs-folder: "docs/"
        pre-build-command: "apt -y install git"
