name: test-sphinx
on:
  pull_request:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1    
    - uses: jmduarte/sphinx-action@main
      with:
        docs-folder: "docs/"
