name: test-sphinx
on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: jmduarte/sphinx-action@main
      env:
        SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v3
      with:
        path: docs/_build/html
