name: test-sphinx
on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Allow for file ownership conflicts with Docker and GitHub Actions
      run: git config --global --add safe.directory '*'
    - uses: jmduarte/sphinx-action@main
      env:
        SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        pre-build-command: "git config --system --add safe.directory '*'"
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v4
      with:
        path: docs/_build/html
