run:
	vivado_hls -f build_prj.tcl
	less myproject_prj/solution1/syn/report/myproject_csynth.rpt

gui: run
	vivado_hls -p myproject_prj

gui-only:
	vivado_hls -p myproject_prj

results:
	less myproject_prj/solution1/syn/report/myproject_csynth.rpt

clean:
	rm -rf myproject_prj *log
